-- Controleurs leggen een feitelijke terugmelding vast zonder een intern
-- intelligence-werkpunt administratief af te handelen.

create table if not exists public.intelligence_werkpunt_terugmeldingen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  werkpunt_id bigint not null
    references public.intelligence_werkpunten(id)
    on update cascade
    on delete cascade,

  controlesessie_id bigint not null
    references public.controlesessies(id)
    on update cascade
    on delete restrict,

  inspectie_id bigint
    references public.inspecties(id)
    on update cascade
    on delete set null,

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete restrict,

  controle_resultaat_id bigint
    references public.controle_resultaten(id)
    on update cascade
    on delete set null,

  uitkomst text not null
    check (
      uitkomst in (
        'gecontroleerd',
        'actie_uitgevoerd',
        'vervolg_nodig'
      )
    ),

  bevinding text not null,

  geregistreerd_door uuid not null
    references public.profiles(id)
    on update cascade
    on delete restrict,

  geregistreerd_door_naam text not null,

  constraint intelligence_werkpunt_terugmelding_bevinding_niet_leeg
    check (length(trim(bevinding)) > 0),

  constraint intelligence_werkpunt_terugmelding_bevinding_lengte
    check (length(bevinding) <= 2000),

  constraint intelligence_werkpunt_terugmelding_een_per_sessie
    unique (werkpunt_id, controlesessie_id)
);

create index if not exists
  intelligence_werkpunt_terugmeldingen_werkpunt_idx
on public.intelligence_werkpunt_terugmeldingen(
  werkpunt_id,
  created_at desc
);

create index if not exists
  intelligence_werkpunt_terugmeldingen_sessie_idx
on public.intelligence_werkpunt_terugmeldingen(
  controlesessie_id,
  created_at desc
);

alter table public.intelligence_werkpunt_terugmeldingen
  enable row level security;

create policy "Intelligence werkpunt terugmeldingen authenticated lezen"
on public.intelligence_werkpunt_terugmeldingen
for select
to authenticated
using (true);

revoke all privileges
on public.intelligence_werkpunt_terugmeldingen
from public, anon, authenticated;

grant select
on public.intelligence_werkpunt_terugmeldingen
to authenticated;

create or replace function public.registreer_intelligence_werkpunt_terugmelding(
  p_werkpunt_id bigint,
  p_controlesessie_id bigint,
  p_uitkomst text,
  p_bevinding text,
  p_woning_controlepunt_id bigint default null
)
returns public.intelligence_werkpunt_terugmeldingen
language plpgsql
security definer
set search_path = public
as $$
declare
  v_werkpunt public.intelligence_werkpunten;
  v_sessie public.controlesessies;
  v_controle_resultaat_id bigint;
  v_naam text;
  v_bevinding text := nullif(trim(coalesce(p_bevinding, '')), '');
  v_resultaat public.intelligence_werkpunt_terugmeldingen;
begin
  if not public.mag_controles_uitvoeren() then
    raise exception 'Geen bevoegdheid om een controleterugmelding vast te leggen.';
  end if;

  if p_uitkomst not in (
    'gecontroleerd',
    'actie_uitgevoerd',
    'vervolg_nodig'
  ) then
    raise exception 'Kies gecontroleerd, actie uitgevoerd of vervolg nodig.';
  end if;

  if v_bevinding is null then
    raise exception 'Een feitelijke bevinding is verplicht.';
  end if;

  if length(v_bevinding) > 2000 then
    raise exception 'De bevinding mag maximaal 2000 tekens bevatten.';
  end if;

  select werkpunt.*
  into v_werkpunt
  from public.intelligence_werkpunten werkpunt
  where werkpunt.id = p_werkpunt_id
    and werkpunt.status = 'actief';

  if not found then
    raise exception 'Dit intelligence-werkpunt is niet meer actief of bestaat niet.';
  end if;

  select sessie.*
  into v_sessie
  from public.controlesessies sessie
  where sessie.id = p_controlesessie_id
    and sessie.status = 'bezig';

  if not found then
    raise exception 'De controlesessie is niet actief.';
  end if;

  if v_sessie.woning_id <> v_werkpunt.woning_id then
    raise exception 'Het werkpunt hoort niet bij de woning van deze controlesessie.';
  end if;

  if v_sessie.controleur_id is not null
    and v_sessie.controleur_id <> auth.uid()
  then
    raise exception 'Deze controlesessie is niet aan jou toegewezen.';
  end if;

  if p_woning_controlepunt_id is not null then
    select resultaat.id
    into v_controle_resultaat_id
    from public.controle_resultaten resultaat
    where resultaat.controlesessie_id = v_sessie.id
      and resultaat.woning_id = v_sessie.woning_id
      and resultaat.woning_controlepunt_id = p_woning_controlepunt_id;

    if not found then
      raise exception 'Het gekozen controlebewijs is nog niet in deze sessie vastgelegd.';
    end if;
  end if;

  select coalesce(
    nullif(trim(profiel.volledige_naam), ''),
    nullif(trim(profiel.email), ''),
    auth.uid()::text
  )
  into v_naam
  from public.profiles profiel
  where profiel.id = auth.uid();

  v_naam := coalesce(v_naam, auth.uid()::text);

  insert into public.intelligence_werkpunt_terugmeldingen (
    werkpunt_id,
    controlesessie_id,
    inspectie_id,
    woning_id,
    controle_resultaat_id,
    uitkomst,
    bevinding,
    geregistreerd_door,
    geregistreerd_door_naam
  )
  values (
    v_werkpunt.id,
    v_sessie.id,
    v_sessie.inspectie_id,
    v_sessie.woning_id,
    v_controle_resultaat_id,
    p_uitkomst,
    v_bevinding,
    auth.uid(),
    v_naam
  )
  returning * into v_resultaat;

  insert into public.workflow_gebeurtenissen (
    woning_id,
    controlesessie_id,
    gebeurtenis_type,
    bron_type,
    bron_id,
    status,
    prioriteit,
    deduplicatie_sleutel,
    payload,
    verwerkt_at
  )
  values (
    v_sessie.woning_id,
    v_sessie.id,
    'controle.werkpunt_teruggemeld',
    'intelligence_werkpunt_terugmelding',
    v_resultaat.id,
    'verwerkt',
    v_werkpunt.prioriteit,
    format('intelligence_werkpunt_terugmelding:%s', v_resultaat.id),
    jsonb_build_object(
      'werkpunt_id', v_werkpunt.id,
      'uitkomst', p_uitkomst,
      'bevinding', v_bevinding,
      'controle_resultaat_id', v_controle_resultaat_id,
      'geregistreerd_door', auth.uid(),
      'feitelijk', true,
      'werkpunt_afgehandeld', false
    ),
    now()
  );

  return v_resultaat;
exception
  when unique_violation then
    raise exception 'Dit werkpunt is tijdens deze controlesessie al teruggemeld.';
end;
$$;

revoke all
on function public.registreer_intelligence_werkpunt_terugmelding(
  bigint,
  bigint,
  text,
  text,
  bigint
)
from public, anon;

grant execute
on function public.registreer_intelligence_werkpunt_terugmelding(
  bigint,
  bigint,
  text,
  text,
  bigint
)
to authenticated;

drop trigger if exists
  audit_intelligence_werkpunt_terugmeldingen_wijzigingen
on public.intelligence_werkpunt_terugmeldingen;

create trigger audit_intelligence_werkpunt_terugmeldingen_wijzigingen
after insert or update or delete
on public.intelligence_werkpunt_terugmeldingen
for each row
execute function public.schrijf_auditlog();

comment on table public.intelligence_werkpunt_terugmeldingen
is 'Onveranderlijke feitelijke terugmeldingen van controleurs op interne intelligence-werkpunten.';

comment on function public.registreer_intelligence_werkpunt_terugmelding(
  bigint,
  bigint,
  text,
  text,
  bigint
)
is 'Legt voor de toegewezen actieve controlesessie een feitelijke terugmelding vast zonder het intelligence-werkpunt af te handelen.';
