create table if not exists public.workflow_gebeurtenissen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint null
    references public.woningen(id)
    on update cascade
    on delete set null,

  controlesessie_id bigint null
    references public.controlesessies(id)
    on update cascade
    on delete set null,

  gebeurtenis_type text not null,
  bron_type text not null,
  bron_id bigint null,

  status text not null default 'nieuw'
    check (
      status in (
        'nieuw',
        'verwerken',
        'verwerkt',
        'mislukt',
        'genegeerd'
      )
    ),

  prioriteit text not null default 'normaal'
    check (
      prioriteit in (
        'laag',
        'normaal',
        'hoog',
        'spoed'
      )
    ),

  deduplicatie_sleutel text not null,
  payload jsonb not null default '{}'::jsonb,

  verwerkt_at timestamptz null,
  foutmelding text null,

  constraint workflow_gebeurtenis_type_niet_leeg
    check (length(trim(gebeurtenis_type)) > 0),

  constraint workflow_bron_type_niet_leeg
    check (length(trim(bron_type)) > 0),

  constraint workflow_deduplicatie_sleutel_niet_leeg
    check (length(trim(deduplicatie_sleutel)) > 0),

  constraint workflow_verwerkt_at_verplicht
    check (
      status <> 'verwerkt'
      or verwerkt_at is not null
    )
);

create unique index if not exists
  workflow_gebeurtenissen_deduplicatie_idx
on public.workflow_gebeurtenissen(deduplicatie_sleutel);

create index if not exists
  workflow_gebeurtenissen_woning_idx
on public.workflow_gebeurtenissen(woning_id);

create index if not exists
  workflow_gebeurtenissen_status_idx
on public.workflow_gebeurtenissen(status, created_at);

create index if not exists
  workflow_gebeurtenissen_bron_idx
on public.workflow_gebeurtenissen(bron_type, bron_id);

create table if not exists public.workflow_acties (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  gebeurtenis_id bigint not null
    references public.workflow_gebeurtenissen(id)
    on update cascade
    on delete restrict,

  taak_id bigint null
    references public.taken(id)
    on update cascade
    on delete set null,

  actie_type text not null,

  status text not null default 'gepland'
    check (
      status in (
        'gepland',
        'uitgevoerd',
        'mislukt',
        'overgeslagen'
      )
    ),

  resultaat jsonb not null default '{}'::jsonb,
  uitgevoerd_at timestamptz null,
  foutmelding text null,

  constraint workflow_actie_type_niet_leeg
    check (length(trim(actie_type)) > 0),

  constraint workflow_actie_uitgevoerd_at_verplicht
    check (
      status <> 'uitgevoerd'
      or uitgevoerd_at is not null
    )
);

create index if not exists
  workflow_acties_gebeurtenis_idx
on public.workflow_acties(gebeurtenis_id);

create index if not exists
  workflow_acties_status_idx
on public.workflow_acties(status, created_at);

create or replace function public.workflow_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();

  if new.status = 'verwerkt' and new.verwerkt_at is null then
    new.verwerkt_at = now();
  end if;

  if new.status <> 'verwerkt' then
    new.verwerkt_at = null;
  end if;

  return new;
end;
$$;

drop trigger if exists workflow_gebeurtenissen_set_updated_at
  on public.workflow_gebeurtenissen;

create trigger workflow_gebeurtenissen_set_updated_at
before update on public.workflow_gebeurtenissen
for each row
execute function public.workflow_set_updated_at();

create or replace function public.workflow_acties_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();

  if new.status = 'uitgevoerd' and new.uitgevoerd_at is null then
    new.uitgevoerd_at = now();
  end if;

  if new.status <> 'uitgevoerd' then
    new.uitgevoerd_at = null;
  end if;

  return new;
end;
$$;

drop trigger if exists workflow_acties_set_updated_at
  on public.workflow_acties;

create trigger workflow_acties_set_updated_at
before update on public.workflow_acties
for each row
execute function public.workflow_acties_set_updated_at();

alter table public.workflow_gebeurtenissen
  enable row level security;

alter table public.workflow_acties
  enable row level security;

drop policy if exists "Workflow gebeurtenissen lezen"
  on public.workflow_gebeurtenissen;

drop policy if exists "Workflow gebeurtenissen toevoegen"
  on public.workflow_gebeurtenissen;

drop policy if exists "Workflow gebeurtenissen wijzigen"
  on public.workflow_gebeurtenissen;

create policy "Workflow gebeurtenissen lezen"
on public.workflow_gebeurtenissen
for select
to anon, authenticated
using (true);

create policy "Workflow gebeurtenissen toevoegen"
on public.workflow_gebeurtenissen
for insert
to anon, authenticated
with check (true);

create policy "Workflow gebeurtenissen wijzigen"
on public.workflow_gebeurtenissen
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Workflow acties lezen"
  on public.workflow_acties;

drop policy if exists "Workflow acties toevoegen"
  on public.workflow_acties;

drop policy if exists "Workflow acties wijzigen"
  on public.workflow_acties;

create policy "Workflow acties lezen"
on public.workflow_acties
for select
to anon, authenticated
using (true);

create policy "Workflow acties toevoegen"
on public.workflow_acties
for insert
to anon, authenticated
with check (true);

create policy "Workflow acties wijzigen"
on public.workflow_acties
for update
to anon, authenticated
using (true)
with check (true);
