create table if not exists public.controlesessies (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete cascade,

  inspectie_id bigint null
    references public.inspecties(id)
    on update cascade
    on delete set null,

  controleur_id uuid null
    references public.profiles(id)
    on update cascade
    on delete set null,

  status text not null default 'gepland'
    check (
      status in (
        'gepland',
        'bezig',
        'afgerond',
        'geannuleerd'
      )
    ),

  gepland_voor timestamptz null,
  gestart_at timestamptz null,
  afgerond_at timestamptz null,

  gemiddelde_controletijd_minuten integer null
    check (
      gemiddelde_controletijd_minuten is null
      or gemiddelde_controletijd_minuten > 0
    ),

  locatie_status text not null default 'niet_geprobeerd'
    check (
      locatie_status in (
        'niet_geprobeerd',
        'beschikbaar',
        'niet_beschikbaar',
        'toestemming_geweigerd',
        'fout'
      )
    ),

  start_latitude double precision null,
  start_longitude double precision null,
  start_nauwkeurigheid_meter double precision null,
  start_afstand_tot_woning_meter double precision null,

  opmerkingen text null,

  constraint controlesessies_tijdvolgorde
    check (
      gestart_at is null
      or afgerond_at is null
      or afgerond_at >= gestart_at
    ),

  constraint controlesessies_bezig_heeft_start
    check (
      status <> 'bezig'
      or gestart_at is not null
    ),

  constraint controlesessies_afgerond_heeft_tijden
    check (
      status <> 'afgerond'
      or (
        gestart_at is not null
        and afgerond_at is not null
      )
    )
);

create index if not exists controlesessies_woning_id_idx
  on public.controlesessies(woning_id);

create index if not exists controlesessies_inspectie_id_idx
  on public.controlesessies(inspectie_id);

create index if not exists controlesessies_controleur_id_idx
  on public.controlesessies(controleur_id);

create index if not exists controlesessies_status_idx
  on public.controlesessies(status);

create index if not exists controlesessies_gepland_voor_idx
  on public.controlesessies(gepland_voor);

create unique index if not exists controlesessies_actieve_inspectie_idx
  on public.controlesessies(inspectie_id)
  where inspectie_id is not null
    and status in ('gepland', 'bezig');

create or replace function public.controlesessies_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();

  if new.status = 'bezig' and new.gestart_at is null then
    new.gestart_at = now();
  end if;

  if new.status = 'afgerond' and new.afgerond_at is null then
    new.afgerond_at = now();
  end if;

  if new.status <> 'afgerond' then
    new.afgerond_at = null;
  end if;

  return new;
end;
$$;

drop trigger if exists controlesessies_set_updated_at
  on public.controlesessies;

create trigger controlesessies_set_updated_at
before insert or update
on public.controlesessies
for each row
execute function public.controlesessies_set_updated_at();

create or replace function public.controleer_controlesessie_koppeling()
returns trigger
language plpgsql
as $$
begin
  if new.inspectie_id is not null and not exists (
    select 1
    from public.inspecties
    where id = new.inspectie_id
      and woning_id = new.woning_id
  ) then
    raise exception
      'De geselecteerde inspectie hoort niet bij deze woning.';
  end if;

  return new;
end;
$$;

drop trigger if exists controlesessies_controle_koppeling
  on public.controlesessies;

create trigger controlesessies_controle_koppeling
before insert or update of woning_id, inspectie_id
on public.controlesessies
for each row
execute function public.controleer_controlesessie_koppeling();

alter table public.controlesessies
enable row level security;

drop policy if exists "Controlesessies lezen"
  on public.controlesessies;

drop policy if exists "Controlesessies toevoegen"
  on public.controlesessies;

drop policy if exists "Controlesessies wijzigen"
  on public.controlesessies;

drop policy if exists "Controlesessies verwijderen"
  on public.controlesessies;

create policy "Controlesessies lezen"
on public.controlesessies
for select
to authenticated
using (true);

create policy "Controlesessies toevoegen"
on public.controlesessies
for insert
to authenticated
with check (public.mag_wijzigen());

create policy "Controlesessies wijzigen"
on public.controlesessies
for update
to authenticated
using (public.mag_wijzigen())
with check (public.mag_wijzigen());

create policy "Controlesessies verwijderen"
on public.controlesessies
for delete
to authenticated
using (public.is_admin());

grant select, insert, update, delete
on public.controlesessies
to authenticated;

grant usage, select
on sequence public.controlesessies_id_seq
to authenticated;
