create table if not exists public.controlebriefings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete cascade,

  controlesessie_id bigint null
    references public.controlesessies(id)
    on update cascade
    on delete set null,

  peildatum date not null default current_date,
  geldig_tot date null,

  status text not null default 'concept'
    check (
      status in (
        'concept',
        'actief',
        'vervangen',
        'vervallen'
      )
    ),

  risicoscore integer not null default 0
    check (risicoscore between 0 and 100),

  risiconiveau text not null default 'laag'
    check (
      risiconiveau in (
        'laag',
        'middel',
        'hoog',
        'kritiek'
      )
    ),

  samenvatting text not null,
  advies text null,

  bronnen jsonb not null default '[]'::jsonb,
  kenmerken jsonb not null default '{}'::jsonb,

  gegenereerd_at timestamptz not null default now(),

  constraint controlebriefing_samenvatting_niet_leeg
    check (length(trim(samenvatting)) > 0),

  constraint controlebriefing_geldigheid
    check (
      geldig_tot is null
      or geldig_tot >= peildatum
    )
);

create unique index if not exists
  controlebriefings_woning_sessie_peildatum_idx
on public.controlebriefings(
  woning_id,
  coalesce(controlesessie_id, 0),
  peildatum
);

create index if not exists
  controlebriefings_woning_status_idx
on public.controlebriefings(
  woning_id,
  status,
  peildatum desc
);

create index if not exists
  controlebriefings_risico_idx
on public.controlebriefings(
  risiconiveau,
  risicoscore desc
);

create table if not exists public.intelligence_werkpunten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete cascade,

  controlebriefing_id bigint null
    references public.controlebriefings(id)
    on update cascade
    on delete set null,

  controlesessie_id bigint null
    references public.controlesessies(id)
    on update cascade
    on delete set null,

  bron_type text not null,
  bron_id bigint null,

  categorie text not null
    check (
      categorie in (
        'inspectie',
        'schade',
        'meldingen',
        'taken',
        'controletijd',
        'orde_netheid',
        'veiligheid',
        'administratie',
        'overig'
      )
    ),

  prioriteit text not null default 'normaal'
    check (
      prioriteit in (
        'laag',
        'normaal',
        'hoog',
        'spoed'
      )
    ),

  status text not null default 'concept'
    check (
      status in (
        'concept',
        'actief',
        'opgevolgd',
        'vervallen',
        'genegeerd'
      )
    ),

  titel text not null,
  omschrijving text not null,

  waarschijnlijkheid numeric null
    check (
      waarschijnlijkheid is null
      or waarschijnlijkheid between 0 and 1
    ),

  deduplicatie_sleutel text not null,

  intern boolean not null default true,

  details jsonb not null default '{}'::jsonb,

  geactiveerd_at timestamptz null,
  opgevolgd_at timestamptz null,

  constraint intelligence_werkpunt_titel_niet_leeg
    check (length(trim(titel)) > 0),

  constraint intelligence_werkpunt_omschrijving_niet_leeg
    check (length(trim(omschrijving)) > 0),

  constraint intelligence_werkpunt_bron_niet_leeg
    check (length(trim(bron_type)) > 0),

  constraint intelligence_werkpunt_deduplicatie_niet_leeg
    check (length(trim(deduplicatie_sleutel)) > 0),

  constraint intelligence_werkpunt_intern
    check (intern = true)
);

create unique index if not exists
  intelligence_werkpunten_deduplicatie_idx
on public.intelligence_werkpunten(
  deduplicatie_sleutel
);

create index if not exists
  intelligence_werkpunten_woning_status_idx
on public.intelligence_werkpunten(
  woning_id,
  status,
  prioriteit,
  created_at desc
);

create index if not exists
  intelligence_werkpunten_briefing_idx
on public.intelligence_werkpunten(
  controlebriefing_id
);

create index if not exists
  intelligence_werkpunten_bron_idx
on public.intelligence_werkpunten(
  bron_type,
  bron_id
);

create or replace function public.intelligence_briefing_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();

  return new;
end;
$$;

drop trigger if exists controlebriefings_set_updated_at
  on public.controlebriefings;

create trigger controlebriefings_set_updated_at
before update on public.controlebriefings
for each row
execute function public.intelligence_briefing_set_updated_at();

drop trigger if exists intelligence_werkpunten_set_updated_at
  on public.intelligence_werkpunten;

create trigger intelligence_werkpunten_set_updated_at
before update on public.intelligence_werkpunten
for each row
execute function public.intelligence_briefing_set_updated_at();

create or replace function public.intelligence_werkpunt_status_bewaken()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'actief'
    and new.geactiveerd_at is null
  then
    new.geactiveerd_at = now();
  end if;

  if new.status <> 'actief' then
    new.geactiveerd_at = null;
  end if;

  if new.status = 'opgevolgd'
    and new.opgevolgd_at is null
  then
    new.opgevolgd_at = now();
  end if;

  if new.status <> 'opgevolgd' then
    new.opgevolgd_at = null;
  end if;

  return new;
end;
$$;

drop trigger if exists intelligence_werkpunten_status_bewaken
  on public.intelligence_werkpunten;

create trigger intelligence_werkpunten_status_bewaken
before insert or update on public.intelligence_werkpunten
for each row
execute function public.intelligence_werkpunt_status_bewaken();

alter table public.controlebriefings
  enable row level security;

alter table public.intelligence_werkpunten
  enable row level security;

drop policy if exists "Controlebriefings lezen"
  on public.controlebriefings;

drop policy if exists "Controlebriefings toevoegen"
  on public.controlebriefings;

drop policy if exists "Controlebriefings wijzigen"
  on public.controlebriefings;

create policy "Controlebriefings lezen"
on public.controlebriefings
for select
to authenticated
using (true);

create policy "Controlebriefings toevoegen"
on public.controlebriefings
for insert
to authenticated
with check (true);

create policy "Controlebriefings wijzigen"
on public.controlebriefings
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Intelligence werkpunten lezen"
  on public.intelligence_werkpunten;

drop policy if exists "Intelligence werkpunten toevoegen"
  on public.intelligence_werkpunten;

drop policy if exists "Intelligence werkpunten wijzigen"
  on public.intelligence_werkpunten;

create policy "Intelligence werkpunten lezen"
on public.intelligence_werkpunten
for select
to authenticated
using (true);

create policy "Intelligence werkpunten toevoegen"
on public.intelligence_werkpunten
for insert
to authenticated
with check (intern = true);

create policy "Intelligence werkpunten wijzigen"
on public.intelligence_werkpunten
for update
to authenticated
using (true)
with check (intern = true);

grant select, insert, update
on public.controlebriefings
to authenticated;

grant select, insert, update
on public.intelligence_werkpunten
to authenticated;
