create table if not exists public.inspectie_fotos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  inspectie_id bigint not null
    references public.inspecties(id)
    on update cascade
    on delete cascade,

  bestandspad text not null unique,
  bestandsnaam text not null,
  mime_type text not null,
  bestandsgrootte bigint not null
    check (bestandsgrootte > 0),

  omschrijving text,
  volgorde integer not null default 0
);

create index if not exists inspectie_fotos_inspectie_id_idx
  on public.inspectie_fotos(inspectie_id);

create index if not exists inspectie_fotos_volgorde_idx
  on public.inspectie_fotos(inspectie_id, volgorde);

alter table public.inspectie_fotos
  enable row level security;

drop policy if exists "Inspectiefotos lezen"
  on public.inspectie_fotos;
drop policy if exists "Inspectiefotos toevoegen"
  on public.inspectie_fotos;
drop policy if exists "Inspectiefotos wijzigen"
  on public.inspectie_fotos;
drop policy if exists "Inspectiefotos verwijderen"
  on public.inspectie_fotos;

create policy "Inspectiefotos lezen"
on public.inspectie_fotos
for select
to authenticated
using (true);

create policy "Inspectiefotos toevoegen"
on public.inspectie_fotos
for insert
to authenticated
with check (
  public.mag_controles_uitvoeren()
);

create policy "Inspectiefotos wijzigen"
on public.inspectie_fotos
for update
to authenticated
using (
  public.mag_controles_uitvoeren()
)
with check (
  public.mag_controles_uitvoeren()
);

create policy "Inspectiefotos verwijderen"
on public.inspectie_fotos
for delete
to authenticated
using (
  public.is_admin()
);

grant select, insert, update, delete
on public.inspectie_fotos
to authenticated;

grant usage, select
on sequence public.inspectie_fotos_id_seq
to authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'inspectiefotos',
  'inspectiefotos',
  false,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/heic',
    'image/heif'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Inspectiefoto bestanden lezen"
  on storage.objects;
drop policy if exists "Inspectiefoto bestanden toevoegen"
  on storage.objects;
drop policy if exists "Inspectiefoto bestanden wijzigen"
  on storage.objects;
drop policy if exists "Inspectiefoto bestanden verwijderen"
  on storage.objects;

create policy "Inspectiefoto bestanden lezen"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'inspectiefotos'
);

create policy "Inspectiefoto bestanden toevoegen"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'inspectiefotos'
  and public.mag_controles_uitvoeren()
);

create policy "Inspectiefoto bestanden wijzigen"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'inspectiefotos'
  and public.mag_controles_uitvoeren()
)
with check (
  bucket_id = 'inspectiefotos'
  and public.mag_controles_uitvoeren()
);

create policy "Inspectiefoto bestanden verwijderen"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'inspectiefotos'
  and public.is_admin()
);
