-- CFME Control 9.0F
-- Compliance Intelligence
-- Objecttype -> verplichting -> certificering/document -> status -> waarschuwing.

-- =========================================================
-- 1. COMPLIANCEVERPLICHTINGEN PER OBJECTTYPE
-- =========================================================

create table if not exists public.objecttype_compliance_verplichtingen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  object_type text not null,
  naam text not null,
  omschrijving text,

  verplichting_type text not null
    check (
      verplichting_type in (
        'certificering',
        'document'
      )
    ),

  certificering_type text
    check (
      certificering_type is null
      or certificering_type in (
        'scope',
        'brandblusser',
        'cv',
        'rookmelder',
        'overig'
      )
    ),

  document_type text
    check (
      document_type is null
      or document_type in (
        'contract',
        'certificering',
        'keuring',
        'inspectie',
        'verzekering',
        'factuur',
        'rapportage',
        'handleiding',
        'identificatie',
        'overig'
      )
    ),

  waarschuwingsdagen integer not null default 30
    check (waarschuwingsdagen between 0 and 365),

  verplicht boolean not null default true,
  actief boolean not null default true,

  opmerkingen text,

  constraint objecttype_compliance_object_type_niet_leeg
    check (length(trim(object_type)) > 0),

  constraint objecttype_compliance_naam_niet_leeg
    check (length(trim(naam)) > 0),

  constraint objecttype_compliance_type_consistent
    check (
      (
        verplichting_type = 'certificering'
        and certificering_type is not null
        and document_type is null
      )
      or
      (
        verplichting_type = 'document'
        and document_type is not null
        and certificering_type is null
      )
    )
);

create unique index if not exists
  objecttype_compliance_certificering_uniek_idx
on public.objecttype_compliance_verplichtingen (
  object_type,
  certificering_type
)
where verplichting_type = 'certificering';

create unique index if not exists
  objecttype_compliance_document_uniek_idx
on public.objecttype_compliance_verplichtingen (
  object_type,
  document_type
)
where verplichting_type = 'document';

create index if not exists
  objecttype_compliance_object_type_idx
on public.objecttype_compliance_verplichtingen (
  object_type,
  actief,
  verplicht
);

create or replace function
  public.objecttype_compliance_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists
  objecttype_compliance_set_updated_at
on public.objecttype_compliance_verplichtingen;

create trigger objecttype_compliance_set_updated_at
before update
on public.objecttype_compliance_verplichtingen
for each row
execute function public.objecttype_compliance_set_updated_at();


-- =========================================================
-- 2. DOCUMENTEN OP OBJECTNIVEAU
-- =========================================================

alter table public.documenten
add column if not exists object_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'documenten_object_id_fkey'
      and conrelid = 'public.documenten'::regclass
  ) then
    alter table public.documenten
    add constraint documenten_object_id_fkey
    foreign key (object_id)
    references public.woning_objecten(id)
    on update cascade
    on delete restrict;
  end if;
end;
$$;

create index if not exists
  documenten_object_id_idx
on public.documenten(object_id);

create or replace function
  public.bewaak_document_object_integriteit()
returns trigger
language plpgsql
as $$
declare
  object_woning_id bigint;
begin
  if new.object_id is null then
    return new;
  end if;

  select woning_id
  into object_woning_id
  from public.woning_objecten
  where id = new.object_id;

  if object_woning_id is null then
    raise exception 'Object bestaat niet.';
  end if;

  if object_woning_id <> new.woning_id then
    raise exception
      'Document en object moeten bij dezelfde woning horen.';
  end if;

  return new;
end;
$$;

drop trigger if exists
  documenten_object_integriteit
on public.documenten;

create trigger documenten_object_integriteit
before insert or update of woning_id, object_id
on public.documenten
for each row
execute function public.bewaak_document_object_integriteit();


-- =========================================================
-- 3. DOCUMENTENOVERZICHT UITBREIDEN
-- =========================================================

create or replace view public.documenten_overzicht
with (security_invoker = true)
as
select
  document.id,
  document.created_at,
  document.updated_at,
  document.woning_id,
  document.titel,
  document.document_type,
  document.omschrijving,
  document.status,
  document.vertrouwelijkheid,
  document.gearchiveerd_op,
  document.archiefreden,
  document.aangemaakt_door,
  document.gewijzigd_door,
  laatste.id as laatste_versie_id,
  laatste.versienummer as laatste_versienummer,
  laatste.created_at as laatste_versie_created_at,
  laatste.bestandspad as laatste_bestandspad,
  laatste.bestandsnaam as laatste_bestandsnaam,
  laatste.mime_type as laatste_mime_type,
  laatste.bestandsgrootte as laatste_bestandsgrootte,
  laatste.versie_opmerking as laatste_versie_opmerking,
  coalesce(versies.aantal, 0)::integer as aantal_versies,
  document.object_id,
  object.naam as object_naam,
  object.object_type,
  object.objectnummer,
  object.ruimte_id,
  ruimte.naam as ruimte_naam
from public.documenten document
left join public.woning_objecten object
  on object.id = document.object_id
left join public.woning_ruimten ruimte
  on ruimte.id = object.ruimte_id
left join lateral (
  select versie.*
  from public.documentversies versie
  where versie.document_id = document.id
  order by versie.versienummer desc
  limit 1
) laatste on true
left join lateral (
  select count(*) as aantal
  from public.documentversies versie
  where versie.document_id = document.id
) versies on true;

-- =========================================================
-- 4. CERTIFICERINGENOVERZICHT UITBREIDEN
-- =========================================================

create or replace view public.certificeringen_overzicht
with (security_invoker = true)
as
select
  certificering.id,
  certificering.created_at,
  certificering.updated_at,
  certificering.woning_id,
  certificering.type,
  certificering.naam,
  certificering.installatie_omschrijving,
  certificering.certificaatnummer,
  certificering.keuringsinstantie,
  certificering.keuringsdatum,
  certificering.geldig_tot,
  certificering.waarschuwingsdagen,
  certificering.actief,
  certificering.ingetrokken_op,
  certificering.reden_inhouding,
  certificering.opmerkingen,
  certificering.aangemaakt_door,
  certificering.gewijzigd_door,
  case
    when certificering.actief = false
      then 'ingetrokken'
    when certificering.geldig_tot < current_date
      then 'verlopen'
    when certificering.geldig_tot
      <= current_date + certificering.waarschuwingsdagen
      then 'verloopt_binnenkort'
    else 'geldig'
  end as compliance_status,
  certificering.geldig_tot - current_date
    as resterende_dagen,
  certificering.object_id,
  object.naam as object_naam,
  object.object_type,
  object.objectnummer,
  object.ruimte_id,
  ruimte.naam as ruimte_naam
from public.certificeringen certificering
left join public.woning_objecten object
  on object.id = certificering.object_id
left join public.woning_ruimten ruimte
  on ruimte.id = object.ruimte_id;

-- =========================================================
-- 5. CENTRAAL OBJECTCOMPLIANCEOVERZICHT
-- =========================================================

create or replace view public.object_compliance_overzicht
with (security_invoker = true)
as
select
  object.id as object_id,
  object.woning_id,
  object.ruimte_id,
  ruimte.naam as ruimte_naam,
  object.object_type,
  object.naam as object_naam,
  object.objectnummer,
  object.merk,
  object.model,
  object.serienummer,

  verplichting.id as verplichting_id,
  verplichting.naam as verplichting_naam,
  verplichting.omschrijving as verplichting_omschrijving,
  verplichting.verplichting_type,
  verplichting.certificering_type,
  verplichting.document_type,
  verplichting.waarschuwingsdagen,
  verplichting.verplicht,

  certificering.id as certificering_id,
  certificering.geldig_tot,
  certificering.actief as certificering_actief,
  certificering.compliance_status
    as certificering_status,

  document.id as document_id,
  document.status as document_status,
  document.laatste_versie_id,
  document.laatste_versie_created_at,

  case
    when verplichting.verplichting_type = 'certificering'
      and certificering.id is null
      then 'ontbreekt'

    when verplichting.verplichting_type = 'certificering'
      and certificering.compliance_status = 'verlopen'
      then 'verlopen'

    when verplichting.verplichting_type = 'certificering'
      and certificering.compliance_status = 'verloopt_binnenkort'
      then 'waarschuwing'

    when verplichting.verplichting_type = 'certificering'
      and certificering.compliance_status = 'ingetrokken'
      then 'ontbreekt'

    when verplichting.verplichting_type = 'certificering'
      and certificering.compliance_status = 'geldig'
      then 'compliant'

    when verplichting.verplichting_type = 'document'
      and document.id is null
      then 'ontbreekt'

    when verplichting.verplichting_type = 'document'
      and document.status = 'gearchiveerd'
      then 'ontbreekt'

    when verplichting.verplichting_type = 'document'
      and document.laatste_versie_id is null
      then 'onvolledig'

    when verplichting.verplichting_type = 'document'
      then 'compliant'

    else 'onbekend'
  end as compliance_status,

  case
    when verplichting.verplichting_type = 'certificering'
      then certificering.geldig_tot - current_date
    else null
  end as resterende_dagen

from public.woning_objecten object
join public.woning_ruimten ruimte
  on ruimte.id = object.ruimte_id
join public.objecttype_compliance_verplichtingen verplichting
  on verplichting.object_type = object.object_type
  and verplichting.actief = true
  and verplichting.verplicht = true

left join lateral (
  select overzicht.*
  from public.certificeringen_overzicht overzicht
  where overzicht.object_id = object.id
    and overzicht.type = verplichting.certificering_type
  order by
    overzicht.actief desc,
    overzicht.geldig_tot desc,
    overzicht.id desc
  limit 1
) certificering
  on verplichting.verplichting_type = 'certificering'

left join lateral (
  select overzicht.*
  from public.documenten_overzicht overzicht
  where overzicht.object_id = object.id
    and overzicht.document_type = verplichting.document_type
  order by
    (overzicht.status = 'actief') desc,
    overzicht.updated_at desc,
    overzicht.id desc
  limit 1
) document
  on verplichting.verplichting_type = 'document'

where object.actief = true;


-- =========================================================
-- 6. SAMENVATTING PER WONING
-- =========================================================

create or replace view public.woning_compliance_samenvatting
with (security_invoker = true)
as
select
  woning_id,
  count(*)::integer as aantal_verplichtingen,
  count(*) filter (
    where compliance_status = 'compliant'
  )::integer as compliant,
  count(*) filter (
    where compliance_status = 'waarschuwing'
  )::integer as waarschuwingen,
  count(*) filter (
    where compliance_status = 'verlopen'
  )::integer as verlopen,
  count(*) filter (
    where compliance_status in (
      'ontbreekt',
      'onvolledig'
    )
  )::integer as ontbrekend,
  case
    when count(*) filter (
      where compliance_status in (
        'verlopen',
        'ontbreekt',
        'onvolledig'
      )
    ) > 0 then 'niet_compliant'

    when count(*) filter (
      where compliance_status = 'waarschuwing'
    ) > 0 then 'aandacht'

    else 'compliant'
  end as compliance_status
from public.object_compliance_overzicht
group by woning_id;


-- =========================================================
-- 7. RLS EN RECHTEN
-- =========================================================

alter table public.objecttype_compliance_verplichtingen
enable row level security;

drop policy if exists
  "Complianceverplichtingen authenticated lezen"
on public.objecttype_compliance_verplichtingen;

create policy
  "Complianceverplichtingen authenticated lezen"
on public.objecttype_compliance_verplichtingen
for select
to authenticated
using (true);

drop policy if exists
  "Complianceverplichtingen bevoegd toevoegen"
on public.objecttype_compliance_verplichtingen;

create policy
  "Complianceverplichtingen bevoegd toevoegen"
on public.objecttype_compliance_verplichtingen
for insert
to authenticated
with check (
  public.mag_administratie_beheren()
);

drop policy if exists
  "Complianceverplichtingen bevoegd wijzigen"
on public.objecttype_compliance_verplichtingen;

create policy
  "Complianceverplichtingen bevoegd wijzigen"
on public.objecttype_compliance_verplichtingen
for update
to authenticated
using (
  public.mag_administratie_beheren()
)
with check (
  public.mag_administratie_beheren()
);

grant select, insert, update
on public.objecttype_compliance_verplichtingen
to authenticated;

grant usage, select
on sequence public.objecttype_compliance_verplichtingen_id_seq
to authenticated;

grant select
on public.object_compliance_overzicht
to authenticated;

grant select
on public.woning_compliance_samenvatting
to authenticated;

grant select
on public.documenten_overzicht
to authenticated;

grant select
on public.certificeringen_overzicht
to authenticated;
