create table if not exists public.taken (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete cascade,

  inspectie_id bigint null
    references public.inspecties(id)
    on update cascade
    on delete set null,

  melding_id bigint null
    references public.meldingen(id)
    on update cascade
    on delete set null,

  titel text not null,
  omschrijving text null,

  categorie text not null default 'overig'
    check (
      categorie in (
        'inspectie',
        'schade',
        'onderhoud',
        'veiligheid',
        'schoonmaak',
        'installatie',
        'administratie',
        'overig'
      )
    ),

  prioriteit text not null default 'normaal'
    check (
      prioriteit in (
        'laag',
        'normaal',
        'hoog',
        'spoed'
      )
    ),

  status text not null default 'open'
    check (
      status in (
        'open',
        'in_behandeling',
        'afgerond',
        'geannuleerd'
      )
    ),

  startdatum date null,
  deadline date null,
  afgerond_op date null,

  toegewezen_aan text null,
  externe_referentie text null,
  opmerkingen text null,

  constraint taken_titel_niet_leeg
    check (length(trim(titel)) > 0),

  constraint taken_deadline_na_startdatum
    check (
      startdatum is null
      or deadline is null
      or deadline >= startdatum
    ),

  constraint taken_afgerond_op_verplicht
    check (
      status <> 'afgerond'
      or afgerond_op is not null
    )
);

create index if not exists taken_woning_id_idx
  on public.taken(woning_id);

create index if not exists taken_inspectie_id_idx
  on public.taken(inspectie_id);

create index if not exists taken_melding_id_idx
  on public.taken(melding_id);

create index if not exists taken_status_idx
  on public.taken(status);

create index if not exists taken_prioriteit_idx
  on public.taken(prioriteit);

create index if not exists taken_deadline_idx
  on public.taken(deadline);

create or replace function public.taken_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();

  if new.status = 'afgerond' and new.afgerond_op is null then
    new.afgerond_op = current_date;
  end if;

  if new.status <> 'afgerond' then
    new.afgerond_op = null;
  end if;

  return new;
end;
$$;

drop trigger if exists taken_set_updated_at
  on public.taken;

create trigger taken_set_updated_at
before update on public.taken
for each row
execute function public.taken_set_updated_at();

alter table public.taken enable row level security;

drop policy if exists "Taken lezen"
  on public.taken;

drop policy if exists "Taken toevoegen"
  on public.taken;

drop policy if exists "Taken wijzigen"
  on public.taken;

drop policy if exists "Taken verwijderen"
  on public.taken;

create policy "Taken lezen"
on public.taken
for select
using (true);

create policy "Taken toevoegen"
on public.taken
for insert
with check (true);

create policy "Taken wijzigen"
on public.taken
for update
using (true)
with check (true);

create policy "Taken verwijderen"
on public.taken
for delete
using (true);
