create table if not exists public.bewoner_kamerhistorie (
  id bigint generated by default as identity primary key,
  bewoner_id bigint not null
    references public.bewoners(id)
    on delete cascade,
  verhuurperiode_id bigint not null,
  oude_kamer_id bigint not null
    references public.kamers(id)
    on delete restrict,
  nieuwe_kamer_id bigint not null
    references public.kamers(id)
    on delete restrict,
  verhuisdatum timestamptz not null default now(),
  created_at timestamptz not null default now(),

  constraint bewoner_kamerhistorie_kamers_verschillend
    check (oude_kamer_id <> nieuwe_kamer_id)
);

create index if not exists bewoner_kamerhistorie_bewoner_id_idx
  on public.bewoner_kamerhistorie(bewoner_id);

create index if not exists bewoner_kamerhistorie_verhuurperiode_id_idx
  on public.bewoner_kamerhistorie(verhuurperiode_id);

create index if not exists bewoner_kamerhistorie_verhuisdatum_idx
  on public.bewoner_kamerhistorie(verhuisdatum desc);

create or replace function public.registreer_bewoner_kamerverhuizing()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if
    old.kamer_id is not null
    and new.kamer_id is not null
    and old.kamer_id is distinct from new.kamer_id
  then
    insert into public.bewoner_kamerhistorie (
      bewoner_id,
      verhuurperiode_id,
      oude_kamer_id,
      nieuwe_kamer_id,
      verhuisdatum
    )
    values (
      new.id,
      new.verhuurperiode_id,
      old.kamer_id,
      new.kamer_id,
      now()
    );
  end if;

  return new;
end;
$$;

drop trigger if exists bewoners_kamerverhuizing_registreren
  on public.bewoners;

create trigger bewoners_kamerverhuizing_registreren
after update of kamer_id
on public.bewoners
for each row
execute function public.registreer_bewoner_kamerverhuizing();

alter table public.bewoner_kamerhistorie enable row level security;

drop policy if exists "Kamerhistorie lezen"
  on public.bewoner_kamerhistorie;

create policy "Kamerhistorie lezen"
on public.bewoner_kamerhistorie
for select
to anon, authenticated
using (true);

drop policy if exists "Kamerhistorie toevoegen"
  on public.bewoner_kamerhistorie;

create policy "Kamerhistorie toevoegen"
on public.bewoner_kamerhistorie
for insert
to anon, authenticated
with check (true);
