create table if not exists public.certificeringen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on delete restrict,

  type text not null
    check (
      type in (
        'scope',
        'brandblusser',
        'cv',
        'rookmelder',
        'overig'
      )
    ),

  naam text not null,
  installatie_omschrijving text,
  certificaatnummer text,
  keuringsinstantie text,

  keuringsdatum date not null,
  geldig_tot date not null,
  waarschuwingsdagen integer not null default 30
    check (
      waarschuwingsdagen between 0 and 365
    ),

  actief boolean not null default true,
  ingetrokken_op date,
  reden_inhouding text,
  opmerkingen text,

  aangemaakt_door uuid
    references auth.users(id)
    on delete set null,

  gewijzigd_door uuid
    references auth.users(id)
    on delete set null,

  constraint certificeringen_datums_geldig
    check (
      geldig_tot >= keuringsdatum
    ),

  constraint certificeringen_intrekking_consistent
    check (
      (
        actief = true
        and ingetrokken_op is null
      )
      or
      (
        actief = false
      )
    )
);

create index if not exists
  certificeringen_woning_id_idx
on public.certificeringen(woning_id);

create index if not exists
  certificeringen_type_idx
on public.certificeringen(type);

create index if not exists
  certificeringen_geldig_tot_idx
on public.certificeringen(geldig_tot);

create index if not exists
  certificeringen_actief_idx
on public.certificeringen(actief);

create unique index if not exists
  certificeringen_een_actieve_per_object_idx
on public.certificeringen (
  woning_id,
  type,
  coalesce(installatie_omschrijving, '')
)
where actief = true;

create or replace function
  public.set_certificeringen_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  new.gewijzigd_door = auth.uid();
  return new;
end;
$$;

drop trigger if exists
  certificeringen_set_updated_at
on public.certificeringen;

create trigger certificeringen_set_updated_at
before update on public.certificeringen
for each row
execute function public.set_certificeringen_updated_at();

create or replace view
  public.certificeringen_overzicht
with (security_invoker = true)
as
select
  certificering.id,
  certificering.created_at,
  certificering.updated_at,
  certificering.woning_id,
  certificering.type,
  certificering.naam,
  certificering.installatie_omschrijving,
  certificering.certificaatnummer,
  certificering.keuringsinstantie,
  certificering.keuringsdatum,
  certificering.geldig_tot,
  certificering.waarschuwingsdagen,
  certificering.actief,
  certificering.ingetrokken_op,
  certificering.reden_inhouding,
  certificering.opmerkingen,
  certificering.aangemaakt_door,
  certificering.gewijzigd_door,
  case
    when certificering.actief = false
      then 'ingetrokken'
    when certificering.geldig_tot < current_date
      then 'verlopen'
    when certificering.geldig_tot
      <= current_date + certificering.waarschuwingsdagen
      then 'verloopt_binnenkort'
    else 'geldig'
  end as compliance_status,
  greatest(
    certificering.geldig_tot - current_date,
    0
  ) as resterende_dagen
from public.certificeringen certificering;

alter table public.certificeringen
enable row level security;

drop policy if exists
  "Certificeringen authenticated lezen"
on public.certificeringen;

create policy
  "Certificeringen authenticated lezen"
on public.certificeringen
for select
to authenticated
using (true);

drop policy if exists
  "Certificeringen bevoegd toevoegen"
on public.certificeringen;

create policy
  "Certificeringen bevoegd toevoegen"
on public.certificeringen
for insert
to authenticated
with check (
  public.mag_administratie_beheren()
  and (
    aangemaakt_door is null
    or aangemaakt_door = auth.uid()
  )
);

drop policy if exists
  "Certificeringen bevoegd wijzigen"
on public.certificeringen;

create policy
  "Certificeringen bevoegd wijzigen"
on public.certificeringen
for update
to authenticated
using (
  public.mag_administratie_beheren()
)
with check (
  public.mag_administratie_beheren()
);

grant select, insert, update
on public.certificeringen
to authenticated;

grant usage, select
on sequence public.certificeringen_id_seq
to authenticated;

grant select
on public.certificeringen_overzicht
to authenticated;
