create table if not exists public.rayons (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  naam text not null,
  code text not null,
  omschrijving text null,
  standaard_controleur_id uuid null
    references public.profiles(id)
    on update cascade
    on delete set null,

  standaard_controlefrequentie_dagen integer not null default 14
    check (
      standaard_controlefrequentie_dagen > 0
    ),

  actief boolean not null default true,

  constraint rayons_naam_niet_leeg
    check (btrim(naam) <> ''),

  constraint rayons_code_niet_leeg
    check (btrim(code) <> '')
);

create unique index if not exists rayons_code_uniek_idx
  on public.rayons(lower(code));

create index if not exists rayons_actief_idx
  on public.rayons(actief);

create index if not exists rayons_standaard_controleur_idx
  on public.rayons(standaard_controleur_id);

create table if not exists public.woning_rayon_toewijzingen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete cascade,

  rayon_id bigint not null
    references public.rayons(id)
    on update cascade
    on delete restrict,

  standaard_controleur_id uuid null
    references public.profiles(id)
    on update cascade
    on delete set null,

  controlefrequentie_dagen integer null
    check (
      controlefrequentie_dagen is null
      or controlefrequentie_dagen > 0
    ),

  geldig_vanaf date not null default current_date,
  geldig_tot date null,

  actief boolean not null default true,
  reden text null,
  opmerkingen text null,

  constraint woning_rayon_toewijzing_geldigheid
    check (
      geldig_tot is null
      or geldig_tot >= geldig_vanaf
    )
);

create index if not exists woning_rayon_woning_idx
  on public.woning_rayon_toewijzingen(woning_id);

create index if not exists woning_rayon_rayon_idx
  on public.woning_rayon_toewijzingen(rayon_id);

create index if not exists woning_rayon_controleur_idx
  on public.woning_rayon_toewijzingen(
    standaard_controleur_id
  );

create index if not exists woning_rayon_geldigheid_idx
  on public.woning_rayon_toewijzingen(
    geldig_vanaf,
    geldig_tot
  );

create unique index if not exists woning_rayon_actief_uniek_idx
  on public.woning_rayon_toewijzingen(woning_id)
  where actief = true
    and geldig_tot is null;

create or replace function public.plan_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rayons_set_updated_at
  on public.rayons;

create trigger rayons_set_updated_at
before update on public.rayons
for each row
execute function public.plan_set_updated_at();

drop trigger if exists woning_rayon_set_updated_at
  on public.woning_rayon_toewijzingen;

create trigger woning_rayon_set_updated_at
before update on public.woning_rayon_toewijzingen
for each row
execute function public.plan_set_updated_at();

create or replace function public.controleer_plan_toewijzing()
returns trigger
language plpgsql
as $$
begin
  if new.standaard_controleur_id is not null
    and not exists (
      select 1
      from public.profiles profiel
      where profiel.id = new.standaard_controleur_id
        and profiel.actief = true
    )
  then
    raise exception
      'De geselecteerde standaardcontroleur is niet actief.';
  end if;

  if new.actief
    and not exists (
      select 1
      from public.rayons rayon
      where rayon.id = new.rayon_id
        and rayon.actief = true
    )
  then
    raise exception
      'De geselecteerde rayon is niet actief.';
  end if;

  return new;
end;
$$;

drop trigger if exists woning_rayon_controle
  on public.woning_rayon_toewijzingen;

create trigger woning_rayon_controle
before insert or update of
  rayon_id,
  standaard_controleur_id,
  actief
on public.woning_rayon_toewijzingen
for each row
execute function public.controleer_plan_toewijzing();

create or replace function public.get_actieve_woningplanning(
  p_woning_id bigint
)
returns table (
  woning_id bigint,
  rayon_id bigint,
  rayon_naam text,
  rayon_code text,
  controleur_id uuid,
  controleur_naam text,
  controleur_email text,
  controlefrequentie_dagen integer,
  geldig_vanaf date
)
language sql
stable
security definer
set search_path = public
as $$
  select
    toewijzing.woning_id,
    rayon.id as rayon_id,
    rayon.naam as rayon_naam,
    rayon.code as rayon_code,
    coalesce(
      toewijzing.standaard_controleur_id,
      rayon.standaard_controleur_id
    ) as controleur_id,
    profiel.volledige_naam as controleur_naam,
    profiel.email as controleur_email,
    coalesce(
      toewijzing.controlefrequentie_dagen,
      rayon.standaard_controlefrequentie_dagen
    ) as controlefrequentie_dagen,
    toewijzing.geldig_vanaf
  from public.woning_rayon_toewijzingen toewijzing
  join public.rayons rayon
    on rayon.id = toewijzing.rayon_id
  left join public.profiles profiel
    on profiel.id = coalesce(
      toewijzing.standaard_controleur_id,
      rayon.standaard_controleur_id
    )
  where toewijzing.woning_id = p_woning_id
    and toewijzing.actief = true
    and toewijzing.geldig_tot is null
    and rayon.actief = true
  limit 1;
$$;

alter table public.rayons
enable row level security;

alter table public.woning_rayon_toewijzingen
enable row level security;

drop policy if exists "Rayons lezen"
  on public.rayons;

create policy "Rayons lezen"
on public.rayons
for select
to authenticated
using (true);

drop policy if exists "Rayons beheren"
  on public.rayons;

create policy "Rayons beheren"
on public.rayons
for all
to authenticated
using (public.mag_wijzigen())
with check (public.mag_wijzigen());

drop policy if exists "Woningrayons lezen"
  on public.woning_rayon_toewijzingen;

create policy "Woningrayons lezen"
on public.woning_rayon_toewijzingen
for select
to authenticated
using (true);

drop policy if exists "Woningrayons beheren"
  on public.woning_rayon_toewijzingen;

create policy "Woningrayons beheren"
on public.woning_rayon_toewijzingen
for all
to authenticated
using (public.mag_wijzigen())
with check (public.mag_wijzigen());

grant select, insert, update
on public.rayons
to authenticated;

grant select, insert, update
on public.woning_rayon_toewijzingen
to authenticated;

grant usage, select
on sequence public.rayons_id_seq
to authenticated;

grant usage, select
on sequence public.woning_rayon_toewijzingen_id_seq
to authenticated;

revoke all
on function public.get_actieve_woningplanning(bigint)
from public;

grant execute
on function public.get_actieve_woningplanning(bigint)
to authenticated;
