create table if not exists public.intelligence_trends (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete cascade,

  trend_type text not null
    check (
      trend_type in (
        'inspectiekwaliteit',
        'orde_netheid',
        'schade',
        'meldingen',
        'taken',
        'controletijd',
        'energie'
      )
    ),

  periode_van date not null,
  periode_tot date not null,

  meetwaarde numeric null,
  referentiewaarde numeric null,
  afwijking_percentage numeric null,

  richting text not null default 'stabiel'
    check (
      richting in (
        'dalend',
        'stabiel',
        'stijgend',
        'onvoldoende_data'
      )
    ),

  ernst text not null default 'informatie'
    check (
      ernst in (
        'informatie',
        'aandacht',
        'hoog',
        'kritiek'
      )
    ),

  bron_aantal integer not null default 0
    check (bron_aantal >= 0),

  toelichting text null,
  details jsonb not null default '{}'::jsonb,

  berekend_at timestamptz not null default now(),

  constraint intelligence_trends_periode_geldig
    check (periode_tot >= periode_van),

  constraint intelligence_trends_uniek
    unique (
      woning_id,
      trend_type,
      periode_van,
      periode_tot
    )
);

create index if not exists
  intelligence_trends_woning_idx
on public.intelligence_trends(
  woning_id,
  periode_tot desc
);

create index if not exists
  intelligence_trends_ernst_idx
on public.intelligence_trends(
  ernst,
  periode_tot desc
);

create table if not exists public.woning_dna_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete cascade,

  peildatum date not null default current_date,

  inspecties_aantal integer not null default 0,
  gemiddelde_orde_netheid numeric null,
  inspecties_met_schade integer not null default 0,

  meldingen_open integer not null default 0,
  meldingen_hoog_spoed integer not null default 0,

  taken_open integer not null default 0,
  taken_over_deadline integer not null default 0,

  gemiddelde_controletijd_minuten numeric null,

  risicoscore integer not null default 0
    check (risicoscore between 0 and 100),

  risiconiveau text not null default 'laag'
    check (
      risiconiveau in (
        'laag',
        'middel',
        'hoog',
        'kritiek'
      )
    ),

  sterke_punten jsonb not null default '[]'::jsonb,
  aandachtspunten jsonb not null default '[]'::jsonb,
  kenmerken jsonb not null default '{}'::jsonb,

  berekend_at timestamptz not null default now(),

  constraint woning_dna_snapshot_uniek
    unique (woning_id, peildatum)
);

create index if not exists
  woning_dna_snapshots_woning_idx
on public.woning_dna_snapshots(
  woning_id,
  peildatum desc
);

create index if not exists
  woning_dna_snapshots_risico_idx
on public.woning_dna_snapshots(
  risiconiveau,
  risicoscore desc
);

create or replace function public.intelligence_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  new.berekend_at = now();
  return new;
end;
$$;

drop trigger if exists intelligence_trends_set_updated_at
  on public.intelligence_trends;

create trigger intelligence_trends_set_updated_at
before update on public.intelligence_trends
for each row
execute function public.intelligence_set_updated_at();

create or replace function public.bereken_woning_dna(
  p_woning_id bigint,
  p_peildatum date default current_date
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inspecties_aantal integer;
  v_gemiddelde_orde_netheid numeric;
  v_inspecties_met_schade integer;

  v_meldingen_open integer;
  v_meldingen_hoog_spoed integer;

  v_taken_open integer;
  v_taken_over_deadline integer;

  v_gemiddelde_controletijd numeric;

  v_risicoscore integer := 0;
  v_risiconiveau text;
  v_snapshot_id bigint;

  v_sterke_punten jsonb := '[]'::jsonb;
  v_aandachtspunten jsonb := '[]'::jsonb;
begin
  if not exists (
    select 1
    from public.woningen
    where id = p_woning_id
  ) then
    raise exception
      'Woning % niet gevonden.',
      p_woning_id;
  end if;

  select
    count(*)::integer,
    round(avg(orde_netheid_score)::numeric, 2),
    count(*) filter (
      where schade_aanwezig = true
    )::integer
  into
    v_inspecties_aantal,
    v_gemiddelde_orde_netheid,
    v_inspecties_met_schade
  from public.inspecties
  where woning_id = p_woning_id
    and inspectiedatum between
      p_peildatum - 180
      and p_peildatum;

  select
    count(*) filter (
      where status <> 'opgelost'
    )::integer,
    count(*) filter (
      where status <> 'opgelost'
        and prioriteit in ('hoog', 'spoed')
    )::integer
  into
    v_meldingen_open,
    v_meldingen_hoog_spoed
  from public.meldingen
  where woning_id = p_woning_id
    and melddatum <= p_peildatum;

  select
    count(*) filter (
      where status in ('open', 'in_behandeling')
    )::integer,
    count(*) filter (
      where status in ('open', 'in_behandeling')
        and deadline is not null
        and deadline < p_peildatum
    )::integer
  into
    v_taken_open,
    v_taken_over_deadline
  from public.taken
  where woning_id = p_woning_id;

  select
    round(
      avg(
        extract(
          epoch from (
            afgerond_at - gestart_at
          )
        ) / 60
      )::numeric,
      2
    )
  into v_gemiddelde_controletijd
  from public.controlesessies
  where woning_id = p_woning_id
    and status = 'afgerond'
    and gestart_at is not null
    and afgerond_at is not null
    and afgerond_at::date between
      p_peildatum - 180
      and p_peildatum;

  v_risicoscore :=
    least(
      100,
      (v_inspecties_met_schade * 8)
      + (v_meldingen_open * 5)
      + (v_meldingen_hoog_spoed * 12)
      + (v_taken_over_deadline * 8)
      + case
          when v_gemiddelde_orde_netheid is null then 5
          when v_gemiddelde_orde_netheid < 2 then 25
          when v_gemiddelde_orde_netheid < 3 then 15
          when v_gemiddelde_orde_netheid < 4 then 5
          else 0
        end
    );

  v_risiconiveau :=
    case
      when v_risicoscore >= 75 then 'kritiek'
      when v_risicoscore >= 50 then 'hoog'
      when v_risicoscore >= 25 then 'middel'
      else 'laag'
    end;

  if (
    v_gemiddelde_orde_netheid is not null
    and v_gemiddelde_orde_netheid >= 4
  ) then
    v_sterke_punten :=
      v_sterke_punten ||
      jsonb_build_array(
        'Structureel goede orde en netheid.'
      );
  end if;

  if v_meldingen_open = 0 then
    v_sterke_punten :=
      v_sterke_punten ||
      jsonb_build_array(
        'Geen open meldingen.'
      );
  end if;

  if v_inspecties_met_schade > 0 then
    v_aandachtspunten :=
      v_aandachtspunten ||
      jsonb_build_array(
        format(
          '%s inspectie(s) met schade in de laatste 180 dagen.',
          v_inspecties_met_schade
        )
      );
  end if;

  if v_meldingen_hoog_spoed > 0 then
    v_aandachtspunten :=
      v_aandachtspunten ||
      jsonb_build_array(
        format(
          '%s open melding(en) met hoge prioriteit of spoed.',
          v_meldingen_hoog_spoed
        )
      );
  end if;

  if v_taken_over_deadline > 0 then
    v_aandachtspunten :=
      v_aandachtspunten ||
      jsonb_build_array(
        format(
          '%s taak/taken over de deadline.',
          v_taken_over_deadline
        )
      );
  end if;

  insert into public.woning_dna_snapshots (
    woning_id,
    peildatum,
    inspecties_aantal,
    gemiddelde_orde_netheid,
    inspecties_met_schade,
    meldingen_open,
    meldingen_hoog_spoed,
    taken_open,
    taken_over_deadline,
    gemiddelde_controletijd_minuten,
    risicoscore,
    risiconiveau,
    sterke_punten,
    aandachtspunten,
    kenmerken,
    berekend_at
  )
  values (
    p_woning_id,
    p_peildatum,
    coalesce(v_inspecties_aantal, 0),
    v_gemiddelde_orde_netheid,
    coalesce(v_inspecties_met_schade, 0),
    coalesce(v_meldingen_open, 0),
    coalesce(v_meldingen_hoog_spoed, 0),
    coalesce(v_taken_open, 0),
    coalesce(v_taken_over_deadline, 0),
    v_gemiddelde_controletijd,
    v_risicoscore,
    v_risiconiveau,
    v_sterke_punten,
    v_aandachtspunten,
    jsonb_build_object(
      'analyseperiode_dagen',
      180,
      'feitelijke_bronnen',
      jsonb_build_array(
        'inspecties',
        'meldingen',
        'taken',
        'controlesessies'
      ),
      'interpretatie',
      true
    ),
    now()
  )
  on conflict (woning_id, peildatum)
  do update
  set
    inspecties_aantal =
      excluded.inspecties_aantal,
    gemiddelde_orde_netheid =
      excluded.gemiddelde_orde_netheid,
    inspecties_met_schade =
      excluded.inspecties_met_schade,
    meldingen_open =
      excluded.meldingen_open,
    meldingen_hoog_spoed =
      excluded.meldingen_hoog_spoed,
    taken_open =
      excluded.taken_open,
    taken_over_deadline =
      excluded.taken_over_deadline,
    gemiddelde_controletijd_minuten =
      excluded.gemiddelde_controletijd_minuten,
    risicoscore =
      excluded.risicoscore,
    risiconiveau =
      excluded.risiconiveau,
    sterke_punten =
      excluded.sterke_punten,
    aandachtspunten =
      excluded.aandachtspunten,
    kenmerken =
      excluded.kenmerken,
    berekend_at = now()
  returning id into v_snapshot_id;

  return v_snapshot_id;
end;
$$;

alter table public.intelligence_trends
  enable row level security;

alter table public.woning_dna_snapshots
  enable row level security;

drop policy if exists "Intelligence trends lezen"
  on public.intelligence_trends;

create policy "Intelligence trends lezen"
on public.intelligence_trends
for select
to authenticated
using (true);

drop policy if exists "Woning DNA lezen"
  on public.woning_dna_snapshots;

create policy "Woning DNA lezen"
on public.woning_dna_snapshots
for select
to authenticated
using (true);

grant select
on public.intelligence_trends
to authenticated;

grant select
on public.woning_dna_snapshots
to authenticated;

grant execute
on function public.bereken_woning_dna(bigint, date)
to authenticated;
