-- 0.8C Auditlog
-- Centraal en onveranderbaar register voor wijzigingen in publieke basistabellen.

create table if not exists public.auditlog (
  id bigint generated by default as identity primary key,
  uitgevoerd_at timestamptz not null default now(),
  gebruiker_id uuid,
  database_rol text not null default current_user,
  actie text not null
    check (actie in ('INSERT', 'UPDATE', 'DELETE')),
  schema_naam text not null,
  tabel_naam text not null,
  record_id text,
  oude_waarden jsonb,
  nieuwe_waarden jsonb,
  gewijzigde_velden text[],
  transactie_id bigint not null default txid_current()
);

create index if not exists auditlog_uitgevoerd_at_idx
  on public.auditlog(uitgevoerd_at desc);

create index if not exists auditlog_gebruiker_id_idx
  on public.auditlog(gebruiker_id);

create index if not exists auditlog_tabel_record_idx
  on public.auditlog(tabel_naam, record_id);

create or replace function public.audit_record_id(
  rij jsonb
)
returns text
language sql
immutable
set search_path = public
as $$
  select coalesce(
    rij ->> 'id',
    rij ->> 'uuid',
    rij ->> 'code'
  );
$$;

create or replace function public.audit_gewijzigde_velden(
  oud jsonb,
  nieuw jsonb
)
returns text[]
language sql
immutable
set search_path = public
as $$
  select coalesce(
    array_agg(sleutel order by sleutel),
    array[]::text[]
  )
  from (
    select sleutel
    from (
      select jsonb_object_keys(coalesce(oud, '{}'::jsonb)) as sleutel
      union
      select jsonb_object_keys(coalesce(nieuw, '{}'::jsonb)) as sleutel
    ) sleutels
    where oud -> sleutel is distinct from nieuw -> sleutel
  ) gewijzigd;
$$;

create or replace function public.schrijf_auditlog()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  oud jsonb;
  nieuw jsonb;
  bron jsonb;
begin
  if tg_op = 'INSERT' then
    oud := null;
    nieuw := to_jsonb(new);
    bron := nieuw;
  elsif tg_op = 'UPDATE' then
    oud := to_jsonb(old);
    nieuw := to_jsonb(new);
    bron := nieuw;

    if oud = nieuw then
      return new;
    end if;
  else
    oud := to_jsonb(old);
    nieuw := null;
    bron := oud;
  end if;

  insert into public.auditlog (
    gebruiker_id,
    database_rol,
    actie,
    schema_naam,
    tabel_naam,
    record_id,
    oude_waarden,
    nieuwe_waarden,
    gewijzigde_velden,
    transactie_id
  )
  values (
    auth.uid(),
    current_user,
    tg_op,
    tg_table_schema,
    tg_table_name,
    public.audit_record_id(bron),
    oud,
    nieuw,
    case
      when tg_op = 'UPDATE'
      then public.audit_gewijzigde_velden(oud, nieuw)
      else array[]::text[]
    end,
    txid_current()
  );

  return coalesce(new, old);
end;
$$;

do $$
declare
  tabel record;
  trigger_naam text;
begin
  for tabel in
    select
      namespace.nspname as schema_naam,
      klasse.relname as tabel_naam
    from pg_class klasse
    join pg_namespace namespace
      on namespace.oid = klasse.relnamespace
    where namespace.nspname = 'public'
      and klasse.relkind in ('r', 'p')
      and klasse.relname <> 'auditlog'
  loop
    trigger_naam :=
      'audit_' || tabel.tabel_naam || '_wijzigingen';

    execute format(
      'drop trigger if exists %I on %I.%I',
      trigger_naam,
      tabel.schema_naam,
      tabel.tabel_naam
    );

    execute format(
      'create trigger %I
       after insert or update or delete on %I.%I
       for each row execute function public.schrijf_auditlog()',
      trigger_naam,
      tabel.schema_naam,
      tabel.tabel_naam
    );
  end loop;
end
$$;

alter table public.auditlog
  enable row level security;

drop policy if exists
  "Auditlog bevoegd lezen"
on public.auditlog;

create policy "Auditlog bevoegd lezen"
on public.auditlog
for select
to authenticated
using (
  public.heeft_rol(
    array['admin', 'management']
  )
);

revoke all privileges
on public.auditlog
from anon;

revoke all privileges
on public.auditlog
from authenticated;

grant select
on public.auditlog
to authenticated;

revoke all
on function public.audit_record_id(jsonb)
from public, anon, authenticated;

revoke all
on function public.audit_gewijzigde_velden(jsonb, jsonb)
from public, anon, authenticated;

revoke all
on function public.schrijf_auditlog()
from public, anon, authenticated;
