create table if not exists public.kamers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  woning_id bigint not null references public.woningen(id) on delete cascade,
  naam text not null,
  verdieping text,
  capaciteit integer not null default 1 check (capaciteit > 0),
  actief boolean not null default true,
  opmerkingen text,
  unique (woning_id, naam)
);

create index if not exists kamers_woning_id_idx
  on public.kamers(woning_id);

create or replace function public.set_kamer_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists kamers_set_updated_at on public.kamers;

create trigger kamers_set_updated_at
before update on public.kamers
for each row
execute function public.set_kamer_updated_at();

alter table public.kamers enable row level security;

drop policy if exists "Kamers lezen" on public.kamers;
drop policy if exists "Kamers toevoegen" on public.kamers;
drop policy if exists "Kamers wijzigen" on public.kamers;
drop policy if exists "Kamers verwijderen" on public.kamers;

create policy "Kamers lezen"
on public.kamers
for select
to anon, authenticated
using (true);

create policy "Kamers toevoegen"
on public.kamers
for insert
to anon, authenticated
with check (true);

create policy "Kamers wijzigen"
on public.kamers
for update
to anon, authenticated
using (true)
with check (true);

create policy "Kamers verwijderen"
on public.kamers
for delete
to anon, authenticated
using (true);
