create table if not exists public.inspecties (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id) on delete cascade,

  verhuurperiode_id bigint
    references public.verhuurperiodes(id) on delete set null,

  type text not null default 'periodiek'
    check (
      type in (
        'begininspectie',
        'periodiek',
        'eindinspectie',
        'incident'
      )
    ),

  inspectiedatum date not null,

  status text not null default 'open'
    check (status in ('open', 'afgerond')),

  algemene_toestand text not null default 'goed'
    check (
      algemene_toestand in (
        'goed',
        'aandacht_nodig',
        'slecht'
      )
    ),

  orde_netheid_score integer not null
    check (orde_netheid_score between 1 and 5),

  schade_aanwezig boolean not null default false,
  schade_omschrijving text,

  uitgevoerd_door text,
  opmerkingen text,

  afgerond_at timestamptz,

  check (
    schade_aanwezig = true
    or schade_omschrijving is null
  ),

  check (
    status = 'open'
    or afgerond_at is not null
  )
);

create index if not exists inspecties_woning_id_idx
  on public.inspecties(woning_id);

create index if not exists inspecties_verhuurperiode_id_idx
  on public.inspecties(verhuurperiode_id);

create index if not exists inspecties_inspectiedatum_idx
  on public.inspecties(inspectiedatum desc);

create index if not exists inspecties_status_idx
  on public.inspecties(status);

create or replace function public.set_inspectie_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();

  if new.status = 'afgerond' and new.afgerond_at is null then
    new.afgerond_at = now();
  end if;

  if new.status = 'open' then
    new.afgerond_at = null;
  end if;

  if new.schade_aanwezig = false then
    new.schade_omschrijving = null;
  end if;

  return new;
end;
$$;

drop trigger if exists inspecties_set_updated_at
  on public.inspecties;

create trigger inspecties_set_updated_at
before insert or update
on public.inspecties
for each row
execute function public.set_inspectie_updated_at();

create or replace function public.controleer_inspectie_koppeling()
returns trigger
language plpgsql
as $$
begin
  if new.verhuurperiode_id is not null and not exists (
    select 1
    from public.verhuurperiodes
    where id = new.verhuurperiode_id
      and woning_id = new.woning_id
  ) then
    raise exception
      'De verhuurperiode hoort niet bij deze woning.';
  end if;

  return new;
end;
$$;

drop trigger if exists inspecties_controle_koppeling
  on public.inspecties;

create trigger inspecties_controle_koppeling
before insert or update of woning_id, verhuurperiode_id
on public.inspecties
for each row
execute function public.controleer_inspectie_koppeling();

alter table public.inspecties enable row level security;

drop policy if exists "Inspecties lezen"
  on public.inspecties;
drop policy if exists "Inspecties toevoegen"
  on public.inspecties;
drop policy if exists "Inspecties wijzigen"
  on public.inspecties;
drop policy if exists "Inspecties verwijderen"
  on public.inspecties;

create policy "Inspecties lezen"
on public.inspecties
for select
to anon, authenticated
using (true);

create policy "Inspecties toevoegen"
on public.inspecties
for insert
to anon, authenticated
with check (true);

create policy "Inspecties wijzigen"
on public.inspecties
for update
to anon, authenticated
using (true)
with check (true);

create policy "Inspecties verwijderen"
on public.inspecties
for delete
to anon, authenticated
using (true);
