create table if not exists public.rapportexports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  maandrapportage_id bigint not null
    references public.maandrapportages(id)
    on delete restrict,

  templateversie_id bigint not null
    references public.rapporttemplateversies(id)
    on delete restrict,

  exportformaat text not null
    check (
      exportformaat in (
        'pdf',
        'xlsx'
      )
    ),

  status text not null default 'aangemaakt'
    check (
      status in (
        'aangemaakt',
        'gereed',
        'mislukt'
      )
    ),

  bestandsnaam text not null,
  mime_type text not null,
  gegenereerd_at timestamptz,
  gegenereerd_door uuid
    references auth.users(id)
    on delete set null,

  foutmelding text,
  metadata jsonb not null default '{}'::jsonb,

  check (btrim(bestandsnaam) <> ''),
  check (btrim(mime_type) <> ''),

  check (
    status <> 'gereed'
    or gegenereerd_at is not null
  ),

  check (
    status <> 'mislukt'
    or foutmelding is not null
  )
);

create index if not exists rapportexports_maandrapportage_id_idx
  on public.rapportexports(
    maandrapportage_id,
    created_at desc
  );

create index if not exists rapportexports_templateversie_id_idx
  on public.rapportexports(templateversie_id);

create index if not exists rapportexports_formaat_idx
  on public.rapportexports(exportformaat);

create index if not exists rapportexports_status_idx
  on public.rapportexports(status);

create or replace function public.set_rapportexport_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rapportexports_set_updated_at
  on public.rapportexports;

create trigger rapportexports_set_updated_at
before update
on public.rapportexports
for each row
execute function public.set_rapportexport_updated_at();

create or replace function public.controleer_rapportexport_koppeling()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.maandrapportages rapportage
    where rapportage.id = new.maandrapportage_id
      and rapportage.templateversie_id =
        new.templateversie_id
  ) then
    raise exception
      'De exporttemplateversie hoort niet bij deze maandrapportage.';
  end if;

  return new;
end;
$$;

drop trigger if exists rapportexports_controle_koppeling
  on public.rapportexports;

create trigger rapportexports_controle_koppeling
before insert or update of
  maandrapportage_id,
  templateversie_id
on public.rapportexports
for each row
execute function public.controleer_rapportexport_koppeling();

alter table public.rapportexports
  enable row level security;

drop policy if exists
  "Rapportexports authenticated lezen"
on public.rapportexports;

create policy "Rapportexports authenticated lezen"
on public.rapportexports
for select
to authenticated
using (true);

drop policy if exists
  "Rapportexports authenticated toevoegen"
on public.rapportexports;

create policy "Rapportexports authenticated toevoegen"
on public.rapportexports
for insert
to authenticated
with check (
  gegenereerd_door = auth.uid()
);

drop policy if exists
  "Rapportexports authenticated wijzigen"
on public.rapportexports;

create policy "Rapportexports authenticated wijzigen"
on public.rapportexports
for update
to authenticated
using (
  gegenereerd_door = auth.uid()
)
with check (
  gegenereerd_door = auth.uid()
);

grant select, insert, update
on public.rapportexports
to authenticated;
