create table if not exists public.meldingen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id) on delete cascade,

  inspectie_id bigint
    references public.inspecties(id) on delete set null,

  titel text not null,
  omschrijving text not null,

  categorie text not null default 'overig'
    check (
      categorie in (
        'schade',
        'onderhoud',
        'veiligheid',
        'schoonmaak',
        'installatie',
        'overig'
      )
    ),

  prioriteit text not null default 'normaal'
    check (
      prioriteit in (
        'laag',
        'normaal',
        'hoog',
        'spoed'
      )
    ),

  status text not null default 'open'
    check (
      status in (
        'open',
        'in_behandeling',
        'opgelost'
      )
    ),

  melddatum date not null default current_date,
  oplosdatum date,

  verantwoordelijke text,
  oplossing text,

  factuur_naar text
    check (
      factuur_naar is null
      or factuur_naar in (
        'cfme',
        'hurend_bedrijf',
        'eigenaar',
        'nog_te_bepalen'
      )
    ),

  extern_referentienummer text,
  opmerkingen text,

  check (
    oplosdatum is null
    or oplosdatum >= melddatum
  ),

  check (
    status <> 'opgelost'
    or oplosdatum is not null
  )
);

create index if not exists meldingen_woning_id_idx
  on public.meldingen(woning_id);

create index if not exists meldingen_inspectie_id_idx
  on public.meldingen(inspectie_id);

create index if not exists meldingen_status_idx
  on public.meldingen(status);

create index if not exists meldingen_prioriteit_idx
  on public.meldingen(prioriteit);

create index if not exists meldingen_melddatum_idx
  on public.meldingen(melddatum desc);

create or replace function public.set_melding_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();

  if new.status <> 'opgelost' then
    new.oplosdatum = null;
  end if;

  return new;
end;
$$;

drop trigger if exists meldingen_set_updated_at
  on public.meldingen;

create trigger meldingen_set_updated_at
before insert or update
on public.meldingen
for each row
execute function public.set_melding_updated_at();

create or replace function public.controleer_melding_koppeling()
returns trigger
language plpgsql
as $$
begin
  if new.inspectie_id is not null and not exists (
    select 1
    from public.inspecties
    where id = new.inspectie_id
      and woning_id = new.woning_id
  ) then
    raise exception
      'De geselecteerde inspectie hoort niet bij deze woning.';
  end if;

  return new;
end;
$$;

drop trigger if exists meldingen_controle_koppeling
  on public.meldingen;

create trigger meldingen_controle_koppeling
before insert or update of woning_id, inspectie_id
on public.meldingen
for each row
execute function public.controleer_melding_koppeling();

alter table public.meldingen enable row level security;

drop policy if exists "Meldingen lezen"
  on public.meldingen;
drop policy if exists "Meldingen toevoegen"
  on public.meldingen;
drop policy if exists "Meldingen wijzigen"
  on public.meldingen;
drop policy if exists "Meldingen verwijderen"
  on public.meldingen;

create policy "Meldingen lezen"
on public.meldingen
for select
to anon, authenticated
using (true);

create policy "Meldingen toevoegen"
on public.meldingen
for insert
to anon, authenticated
with check (true);

create policy "Meldingen wijzigen"
on public.meldingen
for update
to anon, authenticated
using (true)
with check (true);

create policy "Meldingen verwijderen"
on public.meldingen
for delete
to anon, authenticated
using (true);
