create table if not exists public.huurders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  verhuurperiode_id bigint not null references public.verhuurperiodes(id) on delete cascade,
  voornaam text not null,
  tussenvoegsel text,
  achternaam text not null,
  geboortedatum date,
  nationaliteit text,
  telefoon text,
  email text,
  document_type text check (
    document_type is null
    or document_type in ('identiteitskaart', 'paspoort', 'verblijfsdocument', 'overig')
  ),
  documentnummer text,
  opmerkingen text
);

create index if not exists huurders_verhuurperiode_id_idx
  on public.huurders(verhuurperiode_id);

create index if not exists huurders_achternaam_idx
  on public.huurders(achternaam);

create or replace function public.set_huurder_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists huurders_set_updated_at on public.huurders;

create trigger huurders_set_updated_at
before update on public.huurders
for each row
execute function public.set_huurder_updated_at();

create or replace function public.controleer_actieve_verhuurperiode_huurder()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.verhuurperiodes
    where id = new.verhuurperiode_id
      and status = 'actief'
  ) then
    raise exception 'Een huurder kan alleen aan een actieve verhuurperiode worden gekoppeld.';
  end if;

  return new;
end;
$$;

drop trigger if exists huurders_controle_actieve_verhuurperiode
  on public.huurders;

create trigger huurders_controle_actieve_verhuurperiode
before insert or update of verhuurperiode_id
on public.huurders
for each row
execute function public.controleer_actieve_verhuurperiode_huurder();

alter table public.huurders enable row level security;

drop policy if exists "Huurders lezen" on public.huurders;
drop policy if exists "Huurders toevoegen" on public.huurders;
drop policy if exists "Huurders wijzigen" on public.huurders;
drop policy if exists "Huurders verwijderen" on public.huurders;

create policy "Huurders lezen"
on public.huurders
for select
to anon, authenticated
using (true);

create policy "Huurders toevoegen"
on public.huurders
for insert
to anon, authenticated
with check (true);

create policy "Huurders wijzigen"
on public.huurders
for update
to anon, authenticated
using (true)
with check (true);

create policy "Huurders verwijderen"
on public.huurders
for delete
to anon, authenticated
using (true);
