-- CFME Control 9.0F
-- Compliance Intelligence: werkpunten, taken en automatische opvolging.

-- =========================================================
-- 1. COMPLIANCEWERKPUNTEN
-- =========================================================

create table if not exists public.compliance_werkpunten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete restrict,

  object_id bigint not null
    references public.woning_objecten(id)
    on update cascade
    on delete restrict,

  verplichting_id bigint not null
    references public.objecttype_compliance_verplichtingen(id)
    on update cascade
    on delete restrict,

  titel text not null,
  omschrijving text,

  bron_status text not null
    check (
      bron_status in (
        'waarschuwing',
        'verlopen',
        'ontbreekt',
        'onvolledig'
      )
    ),

  prioriteit text not null default 'normaal'
    check (
      prioriteit in (
        'laag',
        'normaal',
        'hoog',
        'spoed'
      )
    ),

  status text not null default 'open'
    check (
      status in (
        'open',
        'opgelost',
        'genegeerd'
      )
    ),

  deadline date,
  opgelost_op timestamptz,
  genegeerd_op timestamptz,
  opmerkingen text,

  constraint compliance_werkpunten_titel_niet_leeg
    check (length(trim(titel)) > 0),

  constraint compliance_werkpunten_status_consistent
    check (
      (
        status = 'open'
        and opgelost_op is null
        and genegeerd_op is null
      )
      or
      (
        status = 'opgelost'
        and opgelost_op is not null
        and genegeerd_op is null
      )
      or
      (
        status = 'genegeerd'
        and genegeerd_op is not null
        and opgelost_op is null
      )
    )
);

create unique index if not exists
  compliance_werkpunten_open_uniek_idx
on public.compliance_werkpunten (
  object_id,
  verplichting_id
)
where status = 'open';

create index if not exists
  compliance_werkpunten_woning_idx
on public.compliance_werkpunten (
  woning_id,
  status,
  deadline
);

create index if not exists
  compliance_werkpunten_object_idx
on public.compliance_werkpunten(object_id);

create index if not exists
  compliance_werkpunten_verplichting_idx
on public.compliance_werkpunten(verplichting_id);


-- =========================================================
-- 2. TAKEN AAN COMPLIANCE KOPPELEN
-- =========================================================

alter table public.taken
add column if not exists object_id bigint;

alter table public.taken
add column if not exists compliance_werkpunt_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'taken_object_id_fkey'
      and conrelid = 'public.taken'::regclass
  ) then
    alter table public.taken
    add constraint taken_object_id_fkey
    foreign key (object_id)
    references public.woning_objecten(id)
    on update cascade
    on delete restrict;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'taken_compliance_werkpunt_id_fkey'
      and conrelid = 'public.taken'::regclass
  ) then
    alter table public.taken
    add constraint taken_compliance_werkpunt_id_fkey
    foreign key (compliance_werkpunt_id)
    references public.compliance_werkpunten(id)
    on update cascade
    on delete restrict;
  end if;
end;
$$;

create index if not exists
  taken_object_id_idx
on public.taken(object_id);

create index if not exists
  taken_compliance_werkpunt_id_idx
on public.taken(compliance_werkpunt_id);

create unique index if not exists
  taken_compliance_actief_uniek_idx
on public.taken(compliance_werkpunt_id)
where compliance_werkpunt_id is not null
  and status in ('open', 'in_behandeling');


-- =========================================================
-- 3. INTEGRITEIT
-- =========================================================

create or replace function
  public.bewaak_compliance_werkpunt_integriteit()
returns trigger
language plpgsql
as $$
declare
  object_woning_id bigint;
  verplichting_object_type text;
  object_object_type text;
begin
  select woning_id, object_type
  into object_woning_id, object_object_type
  from public.woning_objecten
  where id = new.object_id;

  if object_woning_id is null then
    raise exception 'Complianceobject bestaat niet.';
  end if;

  if object_woning_id <> new.woning_id then
    raise exception
      'Compliancewerkpunt en object moeten bij dezelfde woning horen.';
  end if;

  select object_type
  into verplichting_object_type
  from public.objecttype_compliance_verplichtingen
  where id = new.verplichting_id;

  if verplichting_object_type is null then
    raise exception 'Complianceverplichting bestaat niet.';
  end if;

  if verplichting_object_type <> object_object_type then
    raise exception
      'Complianceverplichting past niet bij het objecttype.';
  end if;

  new.updated_at = now();

  if new.status = 'opgelost'
     and new.opgelost_op is null then
    new.opgelost_op = now();
  end if;

  if new.status = 'genegeerd'
     and new.genegeerd_op is null then
    new.genegeerd_op = now();
  end if;

  if new.status = 'open' then
    new.opgelost_op = null;
    new.genegeerd_op = null;
  end if;

  return new;
end;
$$;

drop trigger if exists
  compliance_werkpunten_integriteit
on public.compliance_werkpunten;

create trigger compliance_werkpunten_integriteit
before insert or update
on public.compliance_werkpunten
for each row
execute function
  public.bewaak_compliance_werkpunt_integriteit();


create or replace function
  public.bewaak_taak_compliance_integriteit()
returns trigger
language plpgsql
as $$
declare
  object_woning_id bigint;
  werkpunt_woning_id bigint;
  werkpunt_object_id bigint;
begin
  if new.object_id is not null then
    select woning_id
    into object_woning_id
    from public.woning_objecten
    where id = new.object_id;

    if object_woning_id is null then
      raise exception 'Taakobject bestaat niet.';
    end if;

    if object_woning_id <> new.woning_id then
      raise exception
        'Taak en object moeten bij dezelfde woning horen.';
    end if;
  end if;

  if new.compliance_werkpunt_id is not null then
    select woning_id, object_id
    into werkpunt_woning_id, werkpunt_object_id
    from public.compliance_werkpunten
    where id = new.compliance_werkpunt_id;

    if werkpunt_woning_id is null then
      raise exception 'Compliancewerkpunt bestaat niet.';
    end if;

    if werkpunt_woning_id <> new.woning_id then
      raise exception
        'Taak en compliancewerkpunt moeten bij dezelfde woning horen.';
    end if;

    if new.object_id is null then
      new.object_id = werkpunt_object_id;
    elsif new.object_id <> werkpunt_object_id then
      raise exception
        'Taakobject wijkt af van het compliancewerkpunt.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists
  taken_compliance_integriteit
on public.taken;

create trigger taken_compliance_integriteit
before insert or update of
  woning_id,
  object_id,
  compliance_werkpunt_id
on public.taken
for each row
execute function
  public.bewaak_taak_compliance_integriteit();


-- =========================================================
-- 4. AUTOMATISCHE SYNCHRONISATIE
-- =========================================================

create or replace function
  public.synchroniseer_compliance_voor_woning(
    p_woning_id bigint
  )
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  nieuwe_werkpunten integer := 0;
  bijgewerkte_werkpunten integer := 0;
  opgeloste_werkpunten integer := 0;
  nieuwe_taken integer := 0;
  afgeronde_taken integer := 0;
begin
  if p_woning_id is null or p_woning_id <= 0 then
    raise exception 'Ongeldige woning.';
  end if;

  with kandidaten as (
    select
      overzicht.woning_id,
      overzicht.object_id,
      overzicht.verplichting_id,
      overzicht.object_naam,
      overzicht.verplichting_naam,
      overzicht.verplichting_type,
      overzicht.compliance_status,
      overzicht.geldig_tot,
      case
        when overzicht.compliance_status = 'verlopen'
          then 'hoog'
        when overzicht.compliance_status = 'ontbreekt'
          then 'hoog'
        when overzicht.compliance_status = 'onvolledig'
          then 'normaal'
        else 'normaal'
      end as prioriteit,
      case
        when overzicht.compliance_status in (
          'verlopen',
          'ontbreekt'
        )
          then current_date + 7
        when overzicht.geldig_tot is not null
          then overzicht.geldig_tot
        else current_date + 30
      end as deadline
    from public.object_compliance_overzicht overzicht
    where overzicht.woning_id = p_woning_id
      and overzicht.compliance_status in (
        'waarschuwing',
        'verlopen',
        'ontbreekt',
        'onvolledig'
      )
  ),
  ingevoegd as (
    insert into public.compliance_werkpunten (
      woning_id,
      object_id,
      verplichting_id,
      titel,
      omschrijving,
      bron_status,
      prioriteit,
      status,
      deadline
    )
    select
      kandidaat.woning_id,
      kandidaat.object_id,
      kandidaat.verplichting_id,
      kandidaat.verplichting_naam
        || ' — '
        || kandidaat.object_naam,
      'Automatisch compliancewerkpunt voor '
        || kandidaat.verplichting_type
        || '. Actuele status: '
        || kandidaat.compliance_status
        || '.',
      kandidaat.compliance_status,
      kandidaat.prioriteit,
      'open',
      kandidaat.deadline
    from kandidaten kandidaat
    where not exists (
      select 1
      from public.compliance_werkpunten werkpunt
      where werkpunt.object_id = kandidaat.object_id
        and werkpunt.verplichting_id =
          kandidaat.verplichting_id
        and werkpunt.status = 'open'
    )
    returning id
  )
  select count(*)::integer
  into nieuwe_werkpunten
  from ingevoegd;

  with bijgewerkt as (
    update public.compliance_werkpunten werkpunt
    set
      bron_status = overzicht.compliance_status,
      prioriteit = case
        when overzicht.compliance_status in (
          'verlopen',
          'ontbreekt'
        )
          then 'hoog'
        else 'normaal'
      end,
      deadline = case
        when overzicht.compliance_status in (
          'verlopen',
          'ontbreekt'
        )
          then current_date + 7
        when overzicht.geldig_tot is not null
          then overzicht.geldig_tot
        else current_date + 30
      end,
      updated_at = now()
    from public.object_compliance_overzicht overzicht
    where werkpunt.woning_id = p_woning_id
      and werkpunt.status = 'open'
      and overzicht.object_id = werkpunt.object_id
      and overzicht.verplichting_id =
        werkpunt.verplichting_id
      and overzicht.compliance_status in (
        'waarschuwing',
        'verlopen',
        'ontbreekt',
        'onvolledig'
      )
    returning werkpunt.id
  )
  select count(*)::integer
  into bijgewerkte_werkpunten
  from bijgewerkt;

  with opgelost as (
    update public.compliance_werkpunten werkpunt
    set
      status = 'opgelost',
      opgelost_op = now(),
      updated_at = now()
    where werkpunt.woning_id = p_woning_id
      and werkpunt.status = 'open'
      and not exists (
        select 1
        from public.object_compliance_overzicht overzicht
        where overzicht.object_id = werkpunt.object_id
          and overzicht.verplichting_id =
            werkpunt.verplichting_id
          and overzicht.compliance_status in (
            'waarschuwing',
            'verlopen',
            'ontbreekt',
            'onvolledig'
          )
      )
    returning werkpunt.id
  )
  select count(*)::integer
  into opgeloste_werkpunten
  from opgelost;

  with afgerond as (
    update public.taken taak
    set
      status = 'afgerond',
      afgerond_op = current_date,
      updated_at = now()
    from public.compliance_werkpunten werkpunt
    where taak.compliance_werkpunt_id = werkpunt.id
      and taak.woning_id = p_woning_id
      and taak.status in (
        'open',
        'in_behandeling'
      )
      and werkpunt.status = 'opgelost'
    returning taak.id
  )
  select count(*)::integer
  into afgeronde_taken
  from afgerond;

  with ingevoegd as (
    insert into public.taken (
      woning_id,
      object_id,
      compliance_werkpunt_id,
      titel,
      omschrijving,
      categorie,
      prioriteit,
      status,
      startdatum,
      deadline,
      externe_referentie,
      opmerkingen
    )
    select
      werkpunt.woning_id,
      werkpunt.object_id,
      werkpunt.id,
      werkpunt.titel,
      werkpunt.omschrijving,
      case
        when verplichting.verplichting_type =
          'certificering'
          then 'veiligheid'
        else 'administratie'
      end,
      werkpunt.prioriteit,
      'open',
      current_date,
      werkpunt.deadline,
      'COMPLIANCE-WERKPUNT-'
        || werkpunt.id::text,
      'Automatisch aangemaakt door Compliance Intelligence.'
    from public.compliance_werkpunten werkpunt
    join public.objecttype_compliance_verplichtingen
      verplichting
      on verplichting.id = werkpunt.verplichting_id
    where werkpunt.woning_id = p_woning_id
      and werkpunt.status = 'open'
      and not exists (
        select 1
        from public.taken taak
        where taak.compliance_werkpunt_id =
          werkpunt.id
          and taak.status in (
            'open',
            'in_behandeling'
          )
      )
    returning id
  )
  select count(*)::integer
  into nieuwe_taken
  from ingevoegd;

  return jsonb_build_object(
    'woning_id', p_woning_id,
    'nieuwe_werkpunten', nieuwe_werkpunten,
    'bijgewerkte_werkpunten',
      bijgewerkte_werkpunten,
    'opgeloste_werkpunten',
      opgeloste_werkpunten,
    'nieuwe_taken', nieuwe_taken,
    'afgeronde_taken', afgeronde_taken
  );
end;
$$;


-- =========================================================
-- 5. SYNCHRONISATIE BIJ WIJZIGINGEN
-- =========================================================

create or replace function
  public.trigger_synchroniseer_compliance_woning()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  doel_woning_id bigint;
begin
  doel_woning_id := coalesce(
    new.woning_id,
    old.woning_id
  );

  if doel_woning_id is not null then
    perform public.synchroniseer_compliance_voor_woning(
      doel_woning_id
    );
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists
  certificeringen_compliance_synchronisatie
on public.certificeringen;

create trigger certificeringen_compliance_synchronisatie
after insert or update or delete
on public.certificeringen
for each row
execute function
  public.trigger_synchroniseer_compliance_woning();

drop trigger if exists
  documenten_compliance_synchronisatie
on public.documenten;

create trigger documenten_compliance_synchronisatie
after insert or update or delete
on public.documenten
for each row
execute function
  public.trigger_synchroniseer_compliance_woning();


create or replace function
  public.trigger_synchroniseer_objecttype_compliance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  doel_object_type text;
  woning record;
begin
  doel_object_type := coalesce(
    new.object_type,
    old.object_type
  );

  for woning in
    select distinct object.woning_id
    from public.woning_objecten object
    where object.object_type = doel_object_type
  loop
    perform public.synchroniseer_compliance_voor_woning(
      woning.woning_id
    );
  end loop;

  return coalesce(new, old);
end;
$$;

drop trigger if exists
  objecttype_compliance_synchronisatie
on public.objecttype_compliance_verplichtingen;

create trigger objecttype_compliance_synchronisatie
after insert or update or delete
on public.objecttype_compliance_verplichtingen
for each row
execute function
  public.trigger_synchroniseer_objecttype_compliance();


-- =========================================================
-- 6. WERKPUNTENOVERZICHT
-- =========================================================

create or replace view
  public.compliance_werkpunten_overzicht
with (security_invoker = true)
as
select
  werkpunt.id,
  werkpunt.created_at,
  werkpunt.updated_at,
  werkpunt.woning_id,
  werkpunt.object_id,
  object.ruimte_id,
  ruimte.naam as ruimte_naam,
  object.object_type,
  object.naam as object_naam,
  object.objectnummer,
  werkpunt.verplichting_id,
  verplichting.naam as verplichting_naam,
  verplichting.verplichting_type,
  verplichting.certificering_type,
  verplichting.document_type,
  werkpunt.titel,
  werkpunt.omschrijving,
  werkpunt.bron_status,
  werkpunt.prioriteit,
  werkpunt.status,
  werkpunt.deadline,
  werkpunt.opgelost_op,
  werkpunt.genegeerd_op,
  taak.id as taak_id,
  taak.status as taak_status,
  taak.deadline as taak_deadline
from public.compliance_werkpunten werkpunt
join public.woning_objecten object
  on object.id = werkpunt.object_id
join public.woning_ruimten ruimte
  on ruimte.id = object.ruimte_id
join public.objecttype_compliance_verplichtingen
  verplichting
  on verplichting.id = werkpunt.verplichting_id
left join lateral (
  select taak.*
  from public.taken taak
  where taak.compliance_werkpunt_id = werkpunt.id
  order by
    (
      taak.status in (
        'open',
        'in_behandeling'
      )
    ) desc,
    taak.id desc
  limit 1
) taak on true;


-- =========================================================
-- 7. STANDAARDVERPLICHTINGEN
-- =========================================================

insert into public.objecttype_compliance_verplichtingen (
  object_type,
  naam,
  omschrijving,
  verplichting_type,
  certificering_type,
  document_type,
  waarschuwingsdagen,
  verplicht,
  actief
)
values
  (
    'rookmelder',
    'Geldige rookmeldercontrole',
    'Periodieke controle en geldige registratie van de rookmelder.',
    'certificering',
    'rookmelder',
    null,
    30,
    true,
    true
  ),
  (
    'brandblusser',
    'Geldige brandblusserkeuring',
    'Periodieke keuring van de individuele brandblusser.',
    'certificering',
    'brandblusser',
    null,
    30,
    true,
    true
  ),
  (
    'cv_ketel',
    'Geldige cv-keuring',
    'Periodieke keuring van de cv-ketel.',
    'certificering',
    'cv',
    null,
    30,
    true,
    true
  ),
  (
    'cv-ketel',
    'Geldige cv-keuring',
    'Periodieke keuring van de cv-ketel.',
    'certificering',
    'cv',
    null,
    30,
    true,
    true
  ),
  (
    'ketel',
    'Geldige ketelkeuring',
    'Periodieke keuring van de verwarmingsketel.',
    'certificering',
    'cv',
    null,
    30,
    true,
    true
  ),
  (
    'boiler',
    'Onderhouds- of keuringsbewijs',
    'Actueel bewijs van onderhoud of keuring.',
    'document',
    null,
    'keuring',
    30,
    true,
    true
  ),
  (
    'meterkast',
    'Elektrische installatiekeuring',
    'Geldig keuringsbewijs voor de elektrische installatie.',
    'certificering',
    'scope',
    null,
    60,
    true,
    true
  ),
  (
    'elektrische_installatie',
    'Elektrische installatiekeuring',
    'Geldig keuringsbewijs voor de elektrische installatie.',
    'certificering',
    'scope',
    null,
    60,
    true,
    true
  )
on conflict do nothing;


-- =========================================================
-- 8. RLS EN RECHTEN
-- =========================================================

alter table public.compliance_werkpunten
enable row level security;

drop policy if exists
  "Compliancewerkpunten authenticated lezen"
on public.compliance_werkpunten;

create policy
  "Compliancewerkpunten authenticated lezen"
on public.compliance_werkpunten
for select
to authenticated
using (true);

drop policy if exists
  "Compliancewerkpunten bevoegd toevoegen"
on public.compliance_werkpunten;

create policy
  "Compliancewerkpunten bevoegd toevoegen"
on public.compliance_werkpunten
for insert
to authenticated
with check (
  public.mag_administratie_beheren()
);

drop policy if exists
  "Compliancewerkpunten bevoegd wijzigen"
on public.compliance_werkpunten;

create policy
  "Compliancewerkpunten bevoegd wijzigen"
on public.compliance_werkpunten
for update
to authenticated
using (
  public.mag_administratie_beheren()
)
with check (
  public.mag_administratie_beheren()
);

grant select, insert, update
on public.compliance_werkpunten
to authenticated;

grant usage, select
on sequence public.compliance_werkpunten_id_seq
to authenticated;

grant select
on public.compliance_werkpunten_overzicht
to authenticated;

grant execute
on function
  public.synchroniseer_compliance_voor_woning(bigint)
to authenticated;


-- =========================================================
-- 9. BESTAANDE WONINGEN EENMALIG SYNCHRONISEREN
-- =========================================================

do $$
declare
  woning record;
begin
  for woning in
    select distinct object.woning_id
    from public.woning_objecten object
    where object.actief = true
  loop
    perform public.synchroniseer_compliance_voor_woning(
      woning.woning_id
    );
  end loop;
end;
$$;
