
-- CFME Control 9.0G
-- E-mailwaarschuwingen voor verlopen periodieke controles.
-- Geen toegangsblokkade: uitsluitend signalering en escalatie.

create table if not exists public.controletermijn_email_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete cascade,

  woning_rayon_toewijzing_id bigint not null
    references public.woning_rayon_toewijzingen(id)
    on update cascade
    on delete cascade,

  controleur_id uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  uiterste_controle_datum date not null,

  escalatieniveau text not null
    check (
      escalatieniveau in (
        'waarschuwing',
        'herinnering',
        'escalatie'
      )
    ),

  dagen_te_laat integer not null
    check (dagen_te_laat > 0),

  ontvangers text[] not null
    check (cardinality(ontvangers) > 0),

  provider_bericht_id text,
  verzonden_at timestamptz not null default now(),

  constraint controletermijn_email_log_uniek
    unique (
      woning_id,
      uiterste_controle_datum,
      escalatieniveau
    )
);

create index if not exists
  controletermijn_email_log_woning_idx
on public.controletermijn_email_log(
  woning_id,
  verzonden_at desc
);

create index if not exists
  controletermijn_email_log_datum_idx
on public.controletermijn_email_log(
  uiterste_controle_datum,
  escalatieniveau
);

alter table public.controletermijn_email_log
enable row level security;

revoke all
on public.controletermijn_email_log
from public, anon, authenticated;

grant select, insert
on public.controletermijn_email_log
to service_role;

grant usage, select
on sequence public.controletermijn_email_log_id_seq
to service_role;

create or replace function public.geef_verlopen_controletermijnen(
  p_peildatum date default current_date
)
returns table (
  woning_id bigint,
  woning_rayon_toewijzing_id bigint,
  dossiernummer text,
  adres text,
  postcode text,
  plaats text,
  rayon_naam text,
  rayon_code text,
  controleur_id uuid,
  controleur_naam text,
  controleur_email text,
  controlefrequentie_dagen integer,
  laatste_controle_datum date,
  uiterste_controle_datum date,
  dagen_te_laat integer,
  escalatieniveau text
)
language sql
stable
security definer
set search_path = public
as $$
  with actieve_planning as (
    select
      toewijzing.id as woning_rayon_toewijzing_id,
      toewijzing.woning_id,
      woning.dossiernummer,
      woning.adres,
      woning.postcode,
      woning.plaats,
      rayon.naam as rayon_naam,
      rayon.code as rayon_code,
      coalesce(
        toewijzing.standaard_controleur_id,
        rayon.standaard_controleur_id
      ) as controleur_id,
      coalesce(
        toewijzing.controlefrequentie_dagen,
        rayon.standaard_controlefrequentie_dagen
      ) as controlefrequentie_dagen,
      toewijzing.geldig_vanaf
    from public.woning_rayon_toewijzingen toewijzing
    join public.rayons rayon
      on rayon.id = toewijzing.rayon_id
    join public.woningen woning
      on woning.id = toewijzing.woning_id
    where toewijzing.actief = true
      and toewijzing.geldig_tot is null
      and rayon.actief = true
      and exists (
        select 1
        from public.verhuurperiodes verhuur
        where verhuur.woning_id = toewijzing.woning_id
          and verhuur.status = 'actief'
      )
  ),
  planning_met_laatste_controle as (
    select
      planning.*,
      profiel.volledige_naam as controleur_naam,
      profiel.email as controleur_email,
      laatste.inspectiedatum as laatste_controle_datum,
      case
        when laatste.inspectiedatum is not null
          then (
            laatste.inspectiedatum
            + planning.controlefrequentie_dagen
          )
        else planning.geldig_vanaf
      end as uiterste_controle_datum
    from actieve_planning planning
    left join public.profiles profiel
      on profiel.id = planning.controleur_id
      and profiel.actief = true
    left join lateral (
      select inspectie.inspectiedatum
      from public.inspecties inspectie
      where inspectie.woning_id = planning.woning_id
        and inspectie.status = 'afgerond'
      order by
        inspectie.inspectiedatum desc,
        inspectie.created_at desc
      limit 1
    ) laatste on true
  )
  select
    planning.woning_id,
    planning.woning_rayon_toewijzing_id,
    planning.dossiernummer,
    planning.adres,
    planning.postcode,
    planning.plaats,
    planning.rayon_naam,
    planning.rayon_code,
    planning.controleur_id,
    planning.controleur_naam,
    planning.controleur_email,
    planning.controlefrequentie_dagen,
    planning.laatste_controle_datum,
    planning.uiterste_controle_datum,
    (
      p_peildatum
      - planning.uiterste_controle_datum
    )::integer as dagen_te_laat,
    case
      when (
        p_peildatum
        - planning.uiterste_controle_datum
      ) >= 7
        then 'escalatie'
      when (
        p_peildatum
        - planning.uiterste_controle_datum
      ) >= 3
        then 'herinnering'
      else 'waarschuwing'
    end as escalatieniveau
  from planning_met_laatste_controle planning
  where planning.uiterste_controle_datum < p_peildatum
    and planning.controleur_id is not null
    and nullif(trim(planning.controleur_email), '') is not null;
$$;

revoke all on function
  public.geef_verlopen_controletermijnen(date)
from public, anon, authenticated;

grant execute on function
  public.geef_verlopen_controletermijnen(date)
to service_role;

comment on function
  public.geef_verlopen_controletermijnen(date)
is
  'Geeft verlopen periodieke controles terug op basis van de laatste afgeronde inspectie en de actieve controlefrequentie.';
