create table if not exists public.meterstanden (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id) on delete cascade,

  opnamedatum date not null,
  bewoners_aantal integer not null
    check (bewoners_aantal >= 0),

  elektriciteit_kwh numeric(14, 3),
  gas_m3 numeric(14, 3),
  water_m3 numeric(14, 3),

  opgenomen_door text,
  opmerkingen text,

  unique (woning_id, opnamedatum),

  check (
    elektriciteit_kwh is not null
    or gas_m3 is not null
    or water_m3 is not null
  ),

  check (
    elektriciteit_kwh is null
    or elektriciteit_kwh >= 0
  ),

  check (
    gas_m3 is null
    or gas_m3 >= 0
  ),

  check (
    water_m3 is null
    or water_m3 >= 0
  )
);

create index if not exists meterstanden_woning_id_idx
  on public.meterstanden(woning_id);

create index if not exists meterstanden_opnamedatum_idx
  on public.meterstanden(
    woning_id,
    opnamedatum desc
  );

create or replace function public.set_meterstand_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists meterstanden_set_updated_at
  on public.meterstanden;

create trigger meterstanden_set_updated_at
before update
on public.meterstanden
for each row
execute function public.set_meterstand_updated_at();

alter table public.meterstanden
  enable row level security;

drop policy if exists "Meterstanden lezen"
  on public.meterstanden;
drop policy if exists "Meterstanden toevoegen"
  on public.meterstanden;
drop policy if exists "Meterstanden wijzigen"
  on public.meterstanden;
drop policy if exists "Meterstanden verwijderen"
  on public.meterstanden;

create policy "Meterstanden lezen"
on public.meterstanden
for select
to anon, authenticated
using (true);

create policy "Meterstanden toevoegen"
on public.meterstanden
for insert
to anon, authenticated
with check (true);

create policy "Meterstanden wijzigen"
on public.meterstanden
for update
to anon, authenticated
using (true)
with check (true);

create policy "Meterstanden verwijderen"
on public.meterstanden
for delete
to anon, authenticated
using (true);
