begin;

-- Verplichte controlepunten mogen met een feitelijke uitzonderingsstatus worden afgehandeld.
alter table public.controle_resultaten drop constraint if exists controle_resultaten_resultaat_check;
do $$ declare r record; begin
  for r in select conname from pg_constraint where conrelid='public.controle_resultaten'::regclass and contype='c' and pg_get_constraintdef(oid) ilike '%resultaat%' loop
    execute format('alter table public.controle_resultaten drop constraint %I', r.conname);
  end loop;
end $$;
alter table public.controle_resultaten add constraint controle_resultaten_resultaat_check check (resultaat in (
  'goed','voldoende','onvoldoende','niet_aanwezig','niet_van_toepassing','niet_bereikbaar','niet_afleesbaar','defect','overgeslagen'
));

create table if not exists public.meterstand_correcties (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  meterstand_id bigint not null references public.meterstanden(id) on update cascade on delete restrict,
  woning_id bigint not null references public.woningen(id) on update cascade on delete restrict,
  controlesessie_id bigint references public.controlesessies(id) on update cascade on delete set null,
  gecorrigeerd_door uuid references public.profiles(id) on update cascade on delete set null,
  reden text not null check (btrim(reden) <> ''),
  oude_waarden jsonb not null,
  nieuwe_waarden jsonb not null
);
create index if not exists meterstand_correcties_meterstand_idx on public.meterstand_correcties(meterstand_id, created_at desc);
create index if not exists meterstand_correcties_woning_idx on public.meterstand_correcties(woning_id, created_at desc);
alter table public.meterstand_correcties enable row level security;
create policy "Meterstandcorrecties authenticated lezen" on public.meterstand_correcties for select to authenticated using (true);
grant select on public.meterstand_correcties to authenticated;
revoke insert, update, delete on public.meterstand_correcties from authenticated, anon;

create or replace function public.blokkeer_meterstandcorrectie_wijziging() returns trigger language plpgsql as $$
begin raise exception 'Correctiehistorie is onveranderlijk.'; end; $$;
drop trigger if exists meterstand_correcties_onveranderlijk on public.meterstand_correcties;
create trigger meterstand_correcties_onveranderlijk before update or delete on public.meterstand_correcties for each row execute function public.blokkeer_meterstandcorrectie_wijziging();

create or replace function public.corrigeer_meterstand(
  p_meterstand_id bigint, p_bewoners_aantal integer, p_dagstroom_kwh numeric, p_nachtstroom_kwh numeric, p_gas_m3 numeric, p_water_m3 numeric, p_opmerkingen text, p_reden text
) returns public.meterstanden language plpgsql security definer set search_path=public,pg_temp as $$
declare v_oud public.meterstanden; v_nieuw public.meterstanden;
begin
  if not (public.mag_administratie_beheren() or public.mag_controles_uitvoeren()) then raise exception 'Onvoldoende rechten om een meterstand te corrigeren.'; end if;
  if nullif(btrim(coalesce(p_reden,'')),'') is null then raise exception 'Een reden voor de correctie is verplicht.'; end if;
  select * into v_oud from public.meterstanden where id=p_meterstand_id for update;
  if v_oud.id is null then raise exception 'Meterstand niet gevonden.'; end if;
  if p_bewoners_aantal < 0 or coalesce(p_dagstroom_kwh,0)<0 or coalesce(p_nachtstroom_kwh,0)<0 or coalesce(p_gas_m3,0)<0 or coalesce(p_water_m3,0)<0 then raise exception 'Waarden mogen niet negatief zijn.'; end if;
  insert into public.meterstand_correcties(meterstand_id,woning_id,controlesessie_id,gecorrigeerd_door,reden,oude_waarden,nieuwe_waarden) values (
    v_oud.id,v_oud.woning_id,v_oud.controlesessie_id,auth.uid(),btrim(p_reden),
    jsonb_build_object('bewoners_aantal',v_oud.bewoners_aantal,'dagstroom_kwh',v_oud.dagstroom_kwh,'nachtstroom_kwh',v_oud.nachtstroom_kwh,'gas_m3',v_oud.gas_m3,'water_m3',v_oud.water_m3,'opmerkingen',v_oud.opmerkingen),
    jsonb_build_object('bewoners_aantal',p_bewoners_aantal,'dagstroom_kwh',p_dagstroom_kwh,'nachtstroom_kwh',p_nachtstroom_kwh,'gas_m3',p_gas_m3,'water_m3',p_water_m3,'opmerkingen',p_opmerkingen)
  );
  update public.meterstanden set bewoners_aantal=p_bewoners_aantal,dagstroom_kwh=p_dagstroom_kwh,nachtstroom_kwh=p_nachtstroom_kwh,gas_m3=p_gas_m3,water_m3=p_water_m3,opmerkingen=nullif(btrim(coalesce(p_opmerkingen,'')),''),analyse_status='onvoldoende_data',analyse_resultaat='{}'::jsonb,opvolging_nodig=false,geanalyseerd_at=null where id=v_oud.id returning * into v_nieuw;
  return v_nieuw;
end $$;
revoke all on function public.corrigeer_meterstand(bigint,integer,numeric,numeric,numeric,numeric,text,text) from public,anon;
grant execute on function public.corrigeer_meterstand(bigint,integer,numeric,numeric,numeric,numeric,text,text) to authenticated,service_role;

comment on table public.meterstand_correcties is 'Onveranderlijk auditarchief van meterstandcorrecties; de actuele projectie staat in meterstanden.';
commit;
