create table if not exists public.maandrapportages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id) on delete cascade,

  verhuurperiode_id bigint
    references public.verhuurperiodes(id) on delete set null,

  rapportjaar integer not null
    check (rapportjaar between 2000 and 2100),

  rapportmaand integer not null
    check (rapportmaand between 1 and 12),

  titel text not null,

  status text not null default 'concept'
    check (
      status in (
        'concept',
        'definitief',
        'verzonden'
      )
    ),

  ontvanger_naam text,
  ontvanger_email text,
  opmerkingen text,

  rapport_data jsonb not null default '{}'::jsonb,

  gegenereerd_at timestamptz,
  verzonden_at timestamptz,

  unique (
    woning_id,
    rapportjaar,
    rapportmaand
  ),

  check (
    status = 'concept'
    or gegenereerd_at is not null
  ),

  check (
    status <> 'verzonden'
    or verzonden_at is not null
  )
);

create index if not exists maandrapportages_woning_id_idx
  on public.maandrapportages(woning_id);

create index if not exists maandrapportages_periode_idx
  on public.maandrapportages(
    rapportjaar desc,
    rapportmaand desc
  );

create index if not exists maandrapportages_status_idx
  on public.maandrapportages(status);

create or replace function public.set_maandrapportage_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();

  if new.status = 'concept' then
    new.gegenereerd_at = null;
    new.verzonden_at = null;
  end if;

  if (
    new.status in ('definitief', 'verzonden')
    and new.gegenereerd_at is null
  ) then
    new.gegenereerd_at = now();
  end if;

  if (
    new.status = 'verzonden'
    and new.verzonden_at is null
  ) then
    new.verzonden_at = now();
  end if;

  if new.status <> 'verzonden' then
    new.verzonden_at = null;
  end if;

  return new;
end;
$$;

drop trigger if exists maandrapportages_set_updated_at
  on public.maandrapportages;

create trigger maandrapportages_set_updated_at
before insert or update
on public.maandrapportages
for each row
execute function public.set_maandrapportage_updated_at();

create or replace function public.controleer_maandrapportage_koppeling()
returns trigger
language plpgsql
as $$
begin
  if new.verhuurperiode_id is not null and not exists (
    select 1
    from public.verhuurperiodes
    where id = new.verhuurperiode_id
      and woning_id = new.woning_id
  ) then
    raise exception
      'De verhuurperiode hoort niet bij deze woning.';
  end if;

  return new;
end;
$$;

drop trigger if exists maandrapportages_controle_koppeling
  on public.maandrapportages;

create trigger maandrapportages_controle_koppeling
before insert or update of woning_id, verhuurperiode_id
on public.maandrapportages
for each row
execute function public.controleer_maandrapportage_koppeling();

alter table public.maandrapportages
  enable row level security;

drop policy if exists "Maandrapportages lezen"
  on public.maandrapportages;
drop policy if exists "Maandrapportages toevoegen"
  on public.maandrapportages;
drop policy if exists "Maandrapportages wijzigen"
  on public.maandrapportages;
drop policy if exists "Maandrapportages verwijderen"
  on public.maandrapportages;

create policy "Maandrapportages lezen"
on public.maandrapportages
for select
to anon, authenticated
using (true);

create policy "Maandrapportages toevoegen"
on public.maandrapportages
for insert
to anon, authenticated
with check (true);

create policy "Maandrapportages wijzigen"
on public.maandrapportages
for update
to anon, authenticated
using (true)
with check (true);

create policy "Maandrapportages verwijderen"
on public.maandrapportages
for delete
to anon, authenticated
using (true);
