-- CFME Control 8.1A
-- Gezamenlijke gegevensbasis voor:
-- 1. configureerbare controleurroute;
-- 2. controle per ruimte, object en controlepunt;
-- 3. automatische opvolging;
-- 4. zakelijke maandrapportage.

-- =========================================================
-- 1. VERDIEPINGEN
-- =========================================================

create table if not exists public.woning_verdiepingen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete restrict,

  naam text not null,
  niveau integer not null default 0,
  loopvolgorde integer not null default 0
    check (loopvolgorde >= 0),

  actief boolean not null default true,
  opmerkingen text,

  constraint woning_verdiepingen_naam_niet_leeg
    check (length(trim(naam)) > 0),

  constraint woning_verdiepingen_naam_uniek
    unique (woning_id, naam)
);

create index if not exists
  woning_verdiepingen_woning_idx
on public.woning_verdiepingen(woning_id);

create index if not exists
  woning_verdiepingen_loopvolgorde_idx
on public.woning_verdiepingen(
  woning_id,
  actief,
  loopvolgorde,
  id
);


-- =========================================================
-- 2. RUIMTEN EN FYSIEKE LOOPROUTE
-- =========================================================

create table if not exists public.woning_ruimten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete restrict,

  verdieping_id bigint
    references public.woning_verdiepingen(id)
    on update cascade
    on delete restrict,

  kamer_id bigint
    references public.kamers(id)
    on update cascade
    on delete set null,

  naam text not null,

  ruimte_type text not null default 'overig'
    check (
      ruimte_type in (
        'toegangsdeur',
        'hal',
        'gang',
        'overloop',
        'trap',
        'woonkamer',
        'slaapkamer',
        'keuken',
        'badkamer',
        'toilet',
        'berging',
        'zolder',
        'kelder',
        'technische_ruimte',
        'buitenruimte',
        'overig'
      )
    ),

  loopvolgorde integer not null default 0
    check (loopvolgorde >= 0),

  actief boolean not null default true,
  controle_verplicht boolean not null default true,

  omschrijving text,
  route_instructie text,
  opmerkingen text,

  constraint woning_ruimten_naam_niet_leeg
    check (length(trim(naam)) > 0),

  constraint woning_ruimten_naam_uniek
    unique (woning_id, naam)
);

create index if not exists
  woning_ruimten_woning_idx
on public.woning_ruimten(woning_id);

create index if not exists
  woning_ruimten_verdieping_idx
on public.woning_ruimten(verdieping_id);

create index if not exists
  woning_ruimten_kamer_idx
on public.woning_ruimten(kamer_id);

create index if not exists
  woning_ruimten_looproute_idx
on public.woning_ruimten(
  woning_id,
  actief,
  loopvolgorde,
  id
);


-- =========================================================
-- 3. OBJECTEN EN INSTALLATIES PER RUIMTE
-- =========================================================

create table if not exists public.woning_objecten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete restrict,

  ruimte_id bigint not null
    references public.woning_ruimten(id)
    on update cascade
    on delete restrict,

  object_type text not null,
  naam text not null,

  objectnummer text,
  merk text,
  model text,
  serienummer text,

  loopvolgorde integer not null default 0
    check (loopvolgorde >= 0),

  actief boolean not null default true,
  controle_verplicht boolean not null default true,

  geplaatst_op date,
  vervangen_op date,

  opmerkingen text,

  constraint woning_objecten_type_niet_leeg
    check (length(trim(object_type)) > 0),

  constraint woning_objecten_naam_niet_leeg
    check (length(trim(naam)) > 0),

  constraint woning_objecten_objectnummer_uniek
    unique (woning_id, objectnummer)
);

create index if not exists
  woning_objecten_woning_idx
on public.woning_objecten(woning_id);

create index if not exists
  woning_objecten_ruimte_idx
on public.woning_objecten(
  ruimte_id,
  actief,
  loopvolgorde,
  id
);

create index if not exists
  woning_objecten_type_idx
on public.woning_objecten(object_type);


-- =========================================================
-- 4. HERBRUIKBARE CONTROLEPUNTDEFINITIES
-- =========================================================

create table if not exists public.controlepunt_definities (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  code text not null unique,
  naam text not null,
  omschrijving text,

  categorie text not null default 'algemeen'
    check (
      categorie in (
        'algemeen',
        'netheid',
        'conditie',
        'veiligheid',
        'brandveiligheid',
        'installatie',
        'sanitair',
        'ventilatie',
        'energie',
        'bezetting',
        'schade',
        'overig'
      )
    ),

  standaard_ruimte_type text,
  standaard_object_type text,

  invoertype text not null default 'beoordeling'
    check (
      invoertype in (
        'beoordeling',
        'ja_nee',
        'getal',
        'tekst',
        'datum'
      )
    ),

  actief boolean not null default true,

  foto_verplicht_bij_afwijking boolean not null default true,
  toelichting_verplicht_bij_afwijking boolean not null default true,
  melding_maken_bij_afwijking boolean not null default true,
  taak_maken_bij_afwijking boolean not null default true,

  standaard_prioriteit text not null default 'normaal'
    check (
      standaard_prioriteit in (
        'laag',
        'normaal',
        'hoog',
        'spoed'
      )
    ),

  constraint controlepunt_definities_code_niet_leeg
    check (length(trim(code)) > 0),

  constraint controlepunt_definities_naam_niet_leeg
    check (length(trim(naam)) > 0)
);

create index if not exists
  controlepunt_definities_categorie_idx
on public.controlepunt_definities(categorie);

create index if not exists
  controlepunt_definities_ruimte_type_idx
on public.controlepunt_definities(standaard_ruimte_type);

create index if not exists
  controlepunt_definities_object_type_idx
on public.controlepunt_definities(standaard_object_type);


-- =========================================================
-- 5. GECONFIGUREERDE CONTROLEPUNTEN PER WONING
-- =========================================================

create table if not exists public.woning_controlepunten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete restrict,

  ruimte_id bigint not null
    references public.woning_ruimten(id)
    on update cascade
    on delete restrict,

  object_id bigint
    references public.woning_objecten(id)
    on update cascade
    on delete restrict,

  definitie_id bigint not null
    references public.controlepunt_definities(id)
    on update cascade
    on delete restrict,

  naam_override text,
  omschrijving_override text,

  loopvolgorde integer not null default 0
    check (loopvolgorde >= 0),

  verplicht boolean not null default true,
  actief boolean not null default true,

  foto_verplicht_bij_afwijking boolean,
  toelichting_verplicht_bij_afwijking boolean,
  melding_maken_bij_afwijking boolean,
  taak_maken_bij_afwijking boolean,

  opmerkingen text,

  constraint woning_controlepunten_loopvolgorde_geldig
    check (loopvolgorde >= 0)
);

create unique index if not exists
  woning_controlepunten_ruimte_uniek_idx
on public.woning_controlepunten (
  ruimte_id,
  definitie_id,
  loopvolgorde
)
where object_id is null;

create unique index if not exists
  woning_controlepunten_object_uniek_idx
on public.woning_controlepunten (
  ruimte_id,
  object_id,
  definitie_id,
  loopvolgorde
)
where object_id is not null;

create index if not exists
  woning_controlepunten_woning_idx
on public.woning_controlepunten(woning_id);

create index if not exists
  woning_controlepunten_route_idx
on public.woning_controlepunten(
  ruimte_id,
  actief,
  loopvolgorde,
  id
);

create index if not exists
  woning_controlepunten_object_idx
on public.woning_controlepunten(object_id);


-- =========================================================
-- 6. RESULTATEN PER CONTROLESESSIE
-- =========================================================

create table if not exists public.controle_resultaten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  controlesessie_id bigint not null
    references public.controlesessies(id)
    on update cascade
    on delete cascade,

  inspectie_id bigint
    references public.inspecties(id)
    on update cascade
    on delete set null,

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete restrict,

  ruimte_id bigint not null
    references public.woning_ruimten(id)
    on update cascade
    on delete restrict,

  object_id bigint
    references public.woning_objecten(id)
    on update cascade
    on delete restrict,

  woning_controlepunt_id bigint not null
    references public.woning_controlepunten(id)
    on update cascade
    on delete restrict,

  resultaat text not null
    check (
      resultaat in (
        'goed',
        'voldoende',
        'onvoldoende',
        'niet_aanwezig',
        'niet_van_toepassing',
        'niet_bereikbaar'
      )
    ),

  numerieke_waarde numeric,
  tekstwaarde text,
  datumwaarde date,

  ruimte_naam_snapshot text not null,
  object_naam_snapshot text,
  controlepunt_naam_snapshot text not null,

  beoordeeld_at timestamptz not null default now(),
  beoordeeld_door uuid
    references public.profiles(id)
    on update cascade
    on delete set null,

  opmerkingen text,

  constraint controle_resultaten_uniek
    unique (
      controlesessie_id,
      woning_controlepunt_id
    )
);

create index if not exists
  controle_resultaten_sessie_idx
on public.controle_resultaten(
  controlesessie_id,
  id
);

create index if not exists
  controle_resultaten_woning_idx
on public.controle_resultaten(
  woning_id,
  beoordeeld_at desc
);

create index if not exists
  controle_resultaten_ruimte_idx
on public.controle_resultaten(ruimte_id);

create index if not exists
  controle_resultaten_object_idx
on public.controle_resultaten(object_id);

create index if not exists
  controle_resultaten_afwijkingen_idx
on public.controle_resultaten(resultaat)
where resultaat in (
  'onvoldoende',
  'niet_aanwezig',
  'niet_bereikbaar'
);


-- =========================================================
-- 7. AFWIJKINGEN, OPVOLGING EN FACTURATIE
-- =========================================================

create table if not exists public.controle_afwijkingen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  controle_resultaat_id bigint not null unique
    references public.controle_resultaten(id)
    on update cascade
    on delete cascade,

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete restrict,

  inspectie_id bigint
    references public.inspecties(id)
    on update cascade
    on delete set null,

  controlesessie_id bigint not null
    references public.controlesessies(id)
    on update cascade
    on delete cascade,

  gebrek_type text not null
    check (
      gebrek_type in (
        'vervuiling',
        'beschadiging',
        'defect',
        'lekkage',
        'schimmel',
        'veiligheidsrisico',
        'ontbreekt',
        'niet_bereikbaar',
        'verkeerd_gebruik',
        'normale_slijtage',
        'keuring_verlopen',
        'oorzaak_onbekend',
        'overig'
      )
    ),

  toelichting text not null,

  urgentie text not null default 'normaal'
    check (
      urgentie in (
        'laag',
        'normaal',
        'hoog',
        'spoed'
      )
    ),

  oorzaak_type text
    check (
      oorzaak_type is null
      or oorzaak_type in (
        'bewonersgebruik',
        'technisch_gebrek',
        'normale_slijtage',
        'onderhoud',
        'extern',
        'onbekend'
      )
    ),

  opvolging_nodig boolean not null default true,
  melding_maken boolean not null default true,
  taak_maken boolean not null default true,

  melding_id bigint
    references public.meldingen(id)
    on update cascade
    on delete set null,

  taak_id bigint
    references public.taken(id)
    on update cascade
    on delete set null,

  status text not null default 'open'
    check (
      status in (
        'open',
        'in_opvolging',
        'opgelost',
        'geaccepteerd',
        'niet_relevant'
      )
    ),

  opgelost_at timestamptz,
  oplossing text,

  geschatte_kosten numeric(12, 2)
    check (
      geschatte_kosten is null
      or geschatte_kosten >= 0
    ),

  werkelijke_kosten numeric(12, 2)
    check (
      werkelijke_kosten is null
      or werkelijke_kosten >= 0
    ),

  factuur_naar text
    check (
      factuur_naar is null
      or factuur_naar in (
        'cfme',
        'hurend_bedrijf',
        'eigenaar',
        'nog_te_bepalen'
      )
    ),

  financieel_gevolg text,
  operationeel_gevolg text,

  constraint controle_afwijkingen_toelichting_niet_leeg
    check (length(trim(toelichting)) > 0),

  constraint controle_afwijkingen_oplossing_consistent
    check (
      status <> 'opgelost'
      or (
        opgelost_at is not null
        and oplossing is not null
        and length(trim(oplossing)) > 0
      )
    )
);

create index if not exists
  controle_afwijkingen_woning_idx
on public.controle_afwijkingen(
  woning_id,
  created_at desc
);

create index if not exists
  controle_afwijkingen_status_idx
on public.controle_afwijkingen(status);

create index if not exists
  controle_afwijkingen_urgentie_idx
on public.controle_afwijkingen(urgentie);

create index if not exists
  controle_afwijkingen_melding_idx
on public.controle_afwijkingen(melding_id);

create index if not exists
  controle_afwijkingen_taak_idx
on public.controle_afwijkingen(taak_id);


-- =========================================================
-- 8. FOTO'S KOPPELEN AAN RESULTAAT EN AFWIJKING
-- =========================================================

alter table public.inspectie_fotos
add column if not exists controle_resultaat_id bigint
references public.controle_resultaten(id)
on update cascade
on delete set null;

alter table public.inspectie_fotos
add column if not exists controle_afwijking_id bigint
references public.controle_afwijkingen(id)
on update cascade
on delete set null;

create index if not exists
  inspectie_fotos_controle_resultaat_idx
on public.inspectie_fotos(controle_resultaat_id);

create index if not exists
  inspectie_fotos_controle_afwijking_idx
on public.inspectie_fotos(controle_afwijking_id);


-- =========================================================
-- 9. METERSTANDEN IN DEZELFDE CONTROLEFLOW
-- =========================================================

alter table public.meterstanden
add column if not exists controlesessie_id bigint
references public.controlesessies(id)
on update cascade
on delete set null;

alter table public.meterstanden
add column if not exists elektriciteit_dag_kwh numeric(14, 3);

alter table public.meterstanden
add column if not exists elektriciteit_nacht_kwh numeric(14, 3);

alter table public.meterstanden
drop constraint if exists meterstanden_elektriciteit_dag_geldig;

alter table public.meterstanden
add constraint meterstanden_elektriciteit_dag_geldig
check (
  elektriciteit_dag_kwh is null
  or elektriciteit_dag_kwh >= 0
);

alter table public.meterstanden
drop constraint if exists meterstanden_elektriciteit_nacht_geldig;

alter table public.meterstanden
add constraint meterstanden_elektriciteit_nacht_geldig
check (
  elektriciteit_nacht_kwh is null
  or elektriciteit_nacht_kwh >= 0
);

create index if not exists
  meterstanden_controlesessie_idx
on public.meterstanden(controlesessie_id);

-- Vervang de oorspronkelijke controle zodat dag- en nachtmeters
-- ook zelfstandig als geldige meteropname kunnen worden geregistreerd.
do $$
declare
  constraint_record record;
begin
  for constraint_record in
    select constraint_naam.conname
    from pg_constraint constraint_naam
    where constraint_naam.conrelid = 'public.meterstanden'::regclass
      and constraint_naam.contype = 'c'
      and pg_get_constraintdef(constraint_naam.oid) ilike '%elektriciteit_kwh%'
      and pg_get_constraintdef(constraint_naam.oid) ilike '%gas_m3%'
      and pg_get_constraintdef(constraint_naam.oid) ilike '%water_m3%'
  loop
    execute format(
      'alter table public.meterstanden drop constraint %I',
      constraint_record.conname
    );
  end loop;
end;
$$;

alter table public.meterstanden
drop constraint if exists meterstanden_minimaal_een_stand;

alter table public.meterstanden
add constraint meterstanden_minimaal_een_stand
check (
  elektriciteit_kwh is not null
  or elektriciteit_dag_kwh is not null
  or elektriciteit_nacht_kwh is not null
  or gas_m3 is not null
  or water_m3 is not null
);


-- =========================================================
-- 10. KOPPELING CERTIFICERING AAN INDIVIDUEEL OBJECT
-- =========================================================

alter table public.certificeringen
add column if not exists object_id bigint
references public.woning_objecten(id)
on update cascade
on delete restrict;

create index if not exists
  certificeringen_object_idx
on public.certificeringen(object_id);


-- =========================================================
-- 11. KETENVALIDATIE
-- =========================================================

create or replace function public.controleer_woningroute_koppeling()
returns trigger
language plpgsql
as $$
begin
  if new.verdieping_id is not null and not exists (
    select 1
    from public.woning_verdiepingen verdieping
    where verdieping.id = new.verdieping_id
      and verdieping.woning_id = new.woning_id
  ) then
    raise exception
      'De verdieping hoort niet bij deze woning.';
  end if;

  if new.kamer_id is not null and not exists (
    select 1
    from public.kamers kamer
    where kamer.id = new.kamer_id
      and kamer.woning_id = new.woning_id
  ) then
    raise exception
      'De kamer hoort niet bij deze woning.';
  end if;

  return new;
end;
$$;

drop trigger if exists
  woning_ruimten_controle_koppeling
on public.woning_ruimten;

create trigger
  woning_ruimten_controle_koppeling
before insert or update of woning_id, verdieping_id, kamer_id
on public.woning_ruimten
for each row
execute function public.controleer_woningroute_koppeling();


create or replace function public.controleer_woningobject_koppeling()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.woning_ruimten ruimte
    where ruimte.id = new.ruimte_id
      and ruimte.woning_id = new.woning_id
  ) then
    raise exception
      'De ruimte hoort niet bij deze woning.';
  end if;

  return new;
end;
$$;

drop trigger if exists
  woning_objecten_controle_koppeling
on public.woning_objecten;

create trigger
  woning_objecten_controle_koppeling
before insert or update of woning_id, ruimte_id
on public.woning_objecten
for each row
execute function public.controleer_woningobject_koppeling();


create or replace function public.controleer_woningcontrolepunt_koppeling()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.woning_ruimten ruimte
    where ruimte.id = new.ruimte_id
      and ruimte.woning_id = new.woning_id
  ) then
    raise exception
      'De ruimte hoort niet bij deze woning.';
  end if;

  if new.object_id is not null and not exists (
    select 1
    from public.woning_objecten object
    where object.id = new.object_id
      and object.woning_id = new.woning_id
      and object.ruimte_id = new.ruimte_id
  ) then
    raise exception
      'Het object hoort niet bij deze woning en ruimte.';
  end if;

  return new;
end;
$$;

drop trigger if exists
  woning_controlepunten_controle_koppeling
on public.woning_controlepunten;

create trigger
  woning_controlepunten_controle_koppeling
before insert or update of woning_id, ruimte_id, object_id
on public.woning_controlepunten
for each row
execute function public.controleer_woningcontrolepunt_koppeling();


create or replace function public.controleer_controle_resultaat_koppeling()
returns trigger
language plpgsql
as $$
declare
  sessie_woning_id bigint;
  inspectie_woning_id bigint;
begin
  select woning_id
  into sessie_woning_id
  from public.controlesessies
  where id = new.controlesessie_id;

  if sessie_woning_id is null
     or sessie_woning_id <> new.woning_id then
    raise exception
      'De controlesessie hoort niet bij deze woning.';
  end if;

  if new.inspectie_id is not null then
    select woning_id
    into inspectie_woning_id
    from public.inspecties
    where id = new.inspectie_id;

    if inspectie_woning_id is null
       or inspectie_woning_id <> new.woning_id then
      raise exception
        'De inspectie hoort niet bij deze woning.';
    end if;
  end if;

  if not exists (
    select 1
    from public.woning_controlepunten controlepunt
    where controlepunt.id = new.woning_controlepunt_id
      and controlepunt.woning_id = new.woning_id
      and controlepunt.ruimte_id = new.ruimte_id
      and controlepunt.object_id
          is not distinct from new.object_id
  ) then
    raise exception
      'Het controlepunt hoort niet bij deze woning, ruimte en object.';
  end if;

  return new;
end;
$$;

drop trigger if exists
  controle_resultaten_controle_koppeling
on public.controle_resultaten;

create trigger
  controle_resultaten_controle_koppeling
before insert or update of
  controlesessie_id,
  inspectie_id,
  woning_id,
  ruimte_id,
  object_id,
  woning_controlepunt_id
on public.controle_resultaten
for each row
execute function public.controleer_controle_resultaat_koppeling();



create or replace function public.controleer_controle_afwijking_koppeling()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.controle_resultaten resultaat
    where resultaat.id = new.controle_resultaat_id
      and resultaat.woning_id = new.woning_id
      and resultaat.controlesessie_id = new.controlesessie_id
      and resultaat.inspectie_id is not distinct from new.inspectie_id
  ) then
    raise exception
      'De afwijking hoort niet bij dit controleresultaat, deze woning en controlesessie.';
  end if;

  if new.melding_id is not null and not exists (
    select 1
    from public.meldingen melding
    where melding.id = new.melding_id
      and melding.woning_id = new.woning_id
  ) then
    raise exception
      'De gekoppelde melding hoort niet bij deze woning.';
  end if;

  if new.taak_id is not null and not exists (
    select 1
    from public.taken taak
    where taak.id = new.taak_id
      and taak.woning_id = new.woning_id
  ) then
    raise exception
      'De gekoppelde taak hoort niet bij deze woning.';
  end if;

  return new;
end;
$$;

drop trigger if exists
  controle_afwijkingen_controle_koppeling
on public.controle_afwijkingen;

create trigger
  controle_afwijkingen_controle_koppeling
before insert or update of
  controle_resultaat_id,
  woning_id,
  inspectie_id,
  controlesessie_id,
  melding_id,
  taak_id
on public.controle_afwijkingen
for each row
execute function public.controleer_controle_afwijking_koppeling();


-- =========================================================
-- 12. UPDATED_AT
-- =========================================================

create or replace function public.set_controlemodel_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists woning_verdiepingen_set_updated_at
on public.woning_verdiepingen;

create trigger woning_verdiepingen_set_updated_at
before update on public.woning_verdiepingen
for each row
execute function public.set_controlemodel_updated_at();

drop trigger if exists woning_ruimten_set_updated_at
on public.woning_ruimten;

create trigger woning_ruimten_set_updated_at
before update on public.woning_ruimten
for each row
execute function public.set_controlemodel_updated_at();

drop trigger if exists woning_objecten_set_updated_at
on public.woning_objecten;

create trigger woning_objecten_set_updated_at
before update on public.woning_objecten
for each row
execute function public.set_controlemodel_updated_at();

drop trigger if exists controlepunt_definities_set_updated_at
on public.controlepunt_definities;

create trigger controlepunt_definities_set_updated_at
before update on public.controlepunt_definities
for each row
execute function public.set_controlemodel_updated_at();

drop trigger if exists woning_controlepunten_set_updated_at
on public.woning_controlepunten;

create trigger woning_controlepunten_set_updated_at
before update on public.woning_controlepunten
for each row
execute function public.set_controlemodel_updated_at();

drop trigger if exists controle_resultaten_set_updated_at
on public.controle_resultaten;

create trigger controle_resultaten_set_updated_at
before update on public.controle_resultaten
for each row
execute function public.set_controlemodel_updated_at();

drop trigger if exists controle_afwijkingen_set_updated_at
on public.controle_afwijkingen;

create trigger controle_afwijkingen_set_updated_at
before update on public.controle_afwijkingen
for each row
execute function public.set_controlemodel_updated_at();


-- =========================================================
-- 13. RLS EN RECHTEN
-- =========================================================

alter table public.woning_verdiepingen enable row level security;
alter table public.woning_ruimten enable row level security;
alter table public.woning_objecten enable row level security;
alter table public.controlepunt_definities enable row level security;
alter table public.woning_controlepunten enable row level security;
alter table public.controle_resultaten enable row level security;
alter table public.controle_afwijkingen enable row level security;

create policy "Woningverdiepingen authenticated lezen"
on public.woning_verdiepingen
for select
to authenticated
using (true);

create policy "Woningverdiepingen bevoegd toevoegen"
on public.woning_verdiepingen
for insert
to authenticated
with check (public.mag_wijzigen());

create policy "Woningverdiepingen bevoegd wijzigen"
on public.woning_verdiepingen
for update
to authenticated
using (public.mag_wijzigen())
with check (public.mag_wijzigen());


create policy "Woningruimten authenticated lezen"
on public.woning_ruimten
for select
to authenticated
using (true);

create policy "Woningruimten bevoegd toevoegen"
on public.woning_ruimten
for insert
to authenticated
with check (public.mag_wijzigen());

create policy "Woningruimten bevoegd wijzigen"
on public.woning_ruimten
for update
to authenticated
using (public.mag_wijzigen())
with check (public.mag_wijzigen());


create policy "Woningobjecten authenticated lezen"
on public.woning_objecten
for select
to authenticated
using (true);

create policy "Woningobjecten bevoegd toevoegen"
on public.woning_objecten
for insert
to authenticated
with check (public.mag_wijzigen());

create policy "Woningobjecten bevoegd wijzigen"
on public.woning_objecten
for update
to authenticated
using (public.mag_wijzigen())
with check (public.mag_wijzigen());


create policy "Controlepuntdefinities authenticated lezen"
on public.controlepunt_definities
for select
to authenticated
using (true);

create policy "Controlepuntdefinities bevoegd toevoegen"
on public.controlepunt_definities
for insert
to authenticated
with check (public.mag_wijzigen());

create policy "Controlepuntdefinities bevoegd wijzigen"
on public.controlepunt_definities
for update
to authenticated
using (public.mag_wijzigen())
with check (public.mag_wijzigen());


create policy "Woningcontrolepunten authenticated lezen"
on public.woning_controlepunten
for select
to authenticated
using (true);

create policy "Woningcontrolepunten bevoegd toevoegen"
on public.woning_controlepunten
for insert
to authenticated
with check (public.mag_wijzigen());

create policy "Woningcontrolepunten bevoegd wijzigen"
on public.woning_controlepunten
for update
to authenticated
using (public.mag_wijzigen())
with check (public.mag_wijzigen());


create policy "Controleresultaten authenticated lezen"
on public.controle_resultaten
for select
to authenticated
using (true);

create policy "Controleresultaten bevoegd toevoegen"
on public.controle_resultaten
for insert
to authenticated
with check (public.mag_controles_uitvoeren());

create policy "Controleresultaten bevoegd wijzigen"
on public.controle_resultaten
for update
to authenticated
using (public.mag_controles_uitvoeren())
with check (public.mag_controles_uitvoeren());


create policy "Controleafwijkingen authenticated lezen"
on public.controle_afwijkingen
for select
to authenticated
using (true);

create policy "Controleafwijkingen bevoegd toevoegen"
on public.controle_afwijkingen
for insert
to authenticated
with check (public.mag_controles_uitvoeren());

create policy "Controleafwijkingen bevoegd wijzigen"
on public.controle_afwijkingen
for update
to authenticated
using (
  public.mag_controles_uitvoeren()
  or public.mag_meldingen_beheren()
)
with check (
  public.mag_controles_uitvoeren()
  or public.mag_meldingen_beheren()
);


grant select, insert, update
on public.woning_verdiepingen,
   public.woning_ruimten,
   public.woning_objecten,
   public.controlepunt_definities,
   public.woning_controlepunten,
   public.controle_resultaten,
   public.controle_afwijkingen
to authenticated;

grant usage, select
on sequence public.woning_verdiepingen_id_seq,
   public.woning_ruimten_id_seq,
   public.woning_objecten_id_seq,
   public.controlepunt_definities_id_seq,
   public.woning_controlepunten_id_seq,
   public.controle_resultaten_id_seq,
   public.controle_afwijkingen_id_seq
to authenticated;


-- =========================================================
-- 14. BASISCONTROLEPUNTEN
-- =========================================================

insert into public.controlepunt_definities (
  code,
  naam,
  categorie,
  standaard_ruimte_type,
  standaard_object_type,
  invoertype,
  foto_verplicht_bij_afwijking,
  toelichting_verplicht_bij_afwijking,
  melding_maken_bij_afwijking,
  taak_maken_bij_afwijking,
  standaard_prioriteit
)
values
  (
    'ALG_NETHEID',
    'Algemene netheid',
    'netheid',
    null,
    null,
    'beoordeling',
    true,
    true,
    true,
    true,
    'normaal'
  ),
  (
    'ALG_SCHADE',
    'Zichtbare schade',
    'schade',
    null,
    null,
    'beoordeling',
    true,
    true,
    true,
    true,
    'normaal'
  ),
  (
    'ALG_VEILIGHEID',
    'Veilige en vrije doorgang',
    'veiligheid',
    null,
    null,
    'beoordeling',
    true,
    true,
    true,
    true,
    'hoog'
  ),
  (
    'KEUKEN_HYGIENE',
    'Hygiëne keuken',
    'netheid',
    'keuken',
    null,
    'beoordeling',
    true,
    true,
    true,
    true,
    'normaal'
  ),
  (
    'BADKAMER_HYGIENE',
    'Hygiëne badkamer',
    'netheid',
    'badkamer',
    null,
    'beoordeling',
    true,
    true,
    true,
    true,
    'normaal'
  ),
  (
    'BADKAMER_SCHIMMEL',
    'Schimmelvorming',
    'sanitair',
    'badkamer',
    null,
    'beoordeling',
    true,
    true,
    true,
    true,
    'hoog'
  ),
  (
    'ROOKMELDER_WERKING',
    'Werking rookmelder',
    'brandveiligheid',
    null,
    'rookmelder',
    'beoordeling',
    true,
    true,
    true,
    true,
    'spoed'
  ),
  (
    'BRANDBLUSSER_STATUS',
    'Status brandblusser',
    'brandveiligheid',
    null,
    'brandblusser',
    'beoordeling',
    true,
    true,
    true,
    true,
    'hoog'
  ),
  (
    'CV_WERKING',
    'Werking verwarmingsinstallatie',
    'installatie',
    null,
    'cv_ketel',
    'beoordeling',
    true,
    true,
    true,
    true,
    'hoog'
  ),
  (
    'CV_LEKKAGE',
    'Lekkage verwarmingsinstallatie',
    'installatie',
    null,
    'cv_ketel',
    'beoordeling',
    true,
    true,
    true,
    true,
    'spoed'
  )
on conflict (code) do update
set
  naam = excluded.naam,
  categorie = excluded.categorie,
  standaard_ruimte_type = excluded.standaard_ruimte_type,
  standaard_object_type = excluded.standaard_object_type,
  invoertype = excluded.invoertype,
  foto_verplicht_bij_afwijking =
    excluded.foto_verplicht_bij_afwijking,
  toelichting_verplicht_bij_afwijking =
    excluded.toelichting_verplicht_bij_afwijking,
  melding_maken_bij_afwijking =
    excluded.melding_maken_bij_afwijking,
  taak_maken_bij_afwijking =
    excluded.taak_maken_bij_afwijking,
  standaard_prioriteit =
    excluded.standaard_prioriteit,
  actief = true;
