create table if not exists public.bewoners (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  verhuurperiode_id bigint not null
    references public.verhuurperiodes(id) on delete cascade,

  huurder_id bigint
    references public.huurders(id) on delete set null,

  kamer_id bigint
    references public.kamers(id) on delete set null,

  voornaam text not null,
  tussenvoegsel text,
  achternaam text not null,

  incheckdatum date not null,
  uitcheckdatum date,

  status text not null default 'actief'
    check (status in ('actief', 'uitgecheckt')),

  opmerkingen text,

  check (
    uitcheckdatum is null
    or uitcheckdatum >= incheckdatum
  )
);

create index if not exists bewoners_verhuurperiode_id_idx
  on public.bewoners(verhuurperiode_id);

create index if not exists bewoners_huurder_id_idx
  on public.bewoners(huurder_id);

create index if not exists bewoners_kamer_id_idx
  on public.bewoners(kamer_id);

create index if not exists bewoners_status_idx
  on public.bewoners(status);

create or replace function public.set_bewoner_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists bewoners_set_updated_at
  on public.bewoners;

create trigger bewoners_set_updated_at
before update on public.bewoners
for each row
execute function public.set_bewoner_updated_at();

create or replace function public.controleer_bewoner()
returns trigger
language plpgsql
as $$
declare
  periode_woning_id bigint;
  kamer_capaciteit integer;
  actieve_bezetting integer;
begin
  select woning_id
  into periode_woning_id
  from public.verhuurperiodes
  where id = new.verhuurperiode_id;

  if periode_woning_id is null then
    raise exception 'Verhuurperiode niet gevonden.';
  end if;

  if new.status = 'actief' and not exists (
    select 1
    from public.verhuurperiodes
    where id = new.verhuurperiode_id
      and status = 'actief'
  ) then
    raise exception
      'Een actieve bewoner vereist een actieve verhuurperiode.';
  end if;

  if new.huurder_id is not null and not exists (
    select 1
    from public.huurders
    where id = new.huurder_id
      and verhuurperiode_id = new.verhuurperiode_id
  ) then
    raise exception
      'De geselecteerde huurder hoort niet bij deze verhuurperiode.';
  end if;

  if new.kamer_id is not null then
    select capaciteit
    into kamer_capaciteit
    from public.kamers
    where id = new.kamer_id
      and woning_id = periode_woning_id
      and actief = true;

    if kamer_capaciteit is null then
      raise exception
        'De geselecteerde kamer hoort niet bij deze woning of is niet actief.';
    end if;

    if new.status = 'actief' then
      select count(*)
      into actieve_bezetting
      from public.bewoners
      where kamer_id = new.kamer_id
        and status = 'actief'
        and id <> coalesce(new.id, 0);

      if actieve_bezetting >= kamer_capaciteit then
        raise exception
          'De maximale capaciteit van deze kamer is bereikt.';
      end if;
    end if;
  end if;

  if new.status = 'uitgecheckt' and new.uitcheckdatum is null then
    raise exception
      'Uitcheckdatum is verplicht bij status uitgecheckt.';
  end if;

  if new.status = 'actief' then
    new.uitcheckdatum = null;
  end if;

  return new;
end;
$$;

drop trigger if exists bewoners_controle
  on public.bewoners;

create trigger bewoners_controle
before insert or update
on public.bewoners
for each row
execute function public.controleer_bewoner();

alter table public.bewoners enable row level security;

drop policy if exists "Bewoners lezen" on public.bewoners;
drop policy if exists "Bewoners toevoegen" on public.bewoners;
drop policy if exists "Bewoners wijzigen" on public.bewoners;
drop policy if exists "Bewoners verwijderen" on public.bewoners;

create policy "Bewoners lezen"
on public.bewoners
for select
to anon, authenticated
using (true);

create policy "Bewoners toevoegen"
on public.bewoners
for insert
to anon, authenticated
with check (true);

create policy "Bewoners wijzigen"
on public.bewoners
for update
to anon, authenticated
using (true)
with check (true);

create policy "Bewoners verwijderen"
on public.bewoners
for delete
to anon, authenticated
using (true);
