create table if not exists public.rapportblokken (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  code text not null unique,
  naam text not null,
  omschrijving text,

  bloktype text not null
    check (
      bloktype in (
        'samenvatting',
        'bewoners',
        'inspecties',
        'meldingen',
        'meterstanden',
        'energieverbruik',
        'opmerkingen',
        'vrije_tekst'
      )
    ),

  doelgroep text not null default 'beide'
    check (
      doelgroep in (
        'intern',
        'extern',
        'beide'
      )
    ),

  standaard_zichtbaar boolean not null default true,
  actief boolean not null default true,
  configuratie jsonb not null default '{}'::jsonb,

  check (btrim(code) <> ''),
  check (btrim(naam) <> '')
);

create table if not exists public.rapporttemplates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  code text not null unique,
  naam text not null,
  omschrijving text,

  doelgroep text not null
    check (
      doelgroep in (
        'intern',
        'extern'
      )
    ),

  status text not null default 'concept'
    check (
      status in (
        'concept',
        'actief',
        'gearchiveerd'
      )
    ),

  actief boolean not null default true,

  check (btrim(code) <> ''),
  check (btrim(naam) <> '')
);

create table if not exists public.rapporttemplateversies (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  template_id bigint not null
    references public.rapporttemplates(id)
    on delete restrict,

  versienummer integer not null
    check (versienummer > 0),

  status text not null default 'concept'
    check (
      status in (
        'concept',
        'actief',
        'vervallen'
      )
    ),

  geldig_vanaf date,
  toelichting text,
  configuratie jsonb not null default '{}'::jsonb,

  unique (
    template_id,
    versienummer
  )
);

create table if not exists public.rapporttemplateblokken (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  templateversie_id bigint not null
    references public.rapporttemplateversies(id)
    on delete restrict,

  rapportblok_id bigint not null
    references public.rapportblokken(id)
    on delete restrict,

  volgorde integer not null
    check (volgorde > 0),

  verplicht boolean not null default false,
  zichtbaar boolean not null default true,
  titel_override text,
  configuratie jsonb not null default '{}'::jsonb,

  unique (
    templateversie_id,
    rapportblok_id
  ),

  unique (
    templateversie_id,
    volgorde
  )
);

create index if not exists rapportblokken_actief_idx
  on public.rapportblokken(actief);

create index if not exists rapportblokken_doelgroep_idx
  on public.rapportblokken(doelgroep);

create index if not exists rapporttemplates_status_idx
  on public.rapporttemplates(status);

create index if not exists rapporttemplates_doelgroep_idx
  on public.rapporttemplates(doelgroep);

create index if not exists rapporttemplateversies_template_id_idx
  on public.rapporttemplateversies(template_id);

create unique index if not exists rapporttemplateversies_een_actieve_idx
  on public.rapporttemplateversies(template_id)
  where status = 'actief';

create index if not exists rapporttemplateblokken_versie_idx
  on public.rapporttemplateblokken(
    templateversie_id,
    volgorde
  );

create or replace function public.set_rapportagebibliotheek_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rapportblokken_set_updated_at
  on public.rapportblokken;

create trigger rapportblokken_set_updated_at
before update
on public.rapportblokken
for each row
execute function public.set_rapportagebibliotheek_updated_at();

drop trigger if exists rapporttemplates_set_updated_at
  on public.rapporttemplates;

create trigger rapporttemplates_set_updated_at
before update
on public.rapporttemplates
for each row
execute function public.set_rapportagebibliotheek_updated_at();

drop trigger if exists rapporttemplateversies_set_updated_at
  on public.rapporttemplateversies;

create trigger rapporttemplateversies_set_updated_at
before update
on public.rapporttemplateversies
for each row
execute function public.set_rapportagebibliotheek_updated_at();

insert into public.rapportblokken (
  code,
  naam,
  omschrijving,
  bloktype,
  doelgroep,
  standaard_zichtbaar
)
values
  (
    'samenvatting',
    'Samenvatting',
    'Kerncijfers van bewoners, inspecties, meldingen en schades.',
    'samenvatting',
    'beide',
    true
  ),
  (
    'bewoners',
    'Bewoners',
    'Bewoners en kamerbezetting binnen de rapportperiode.',
    'bewoners',
    'beide',
    true
  ),
  (
    'inspecties',
    'Inspecties',
    'Uitgevoerde inspecties, toestand, orde, netheid en schade.',
    'inspecties',
    'beide',
    true
  ),
  (
    'meldingen',
    'Meldingen',
    'Meldingen, schades, oplossingen en factuurverantwoordelijkheid.',
    'meldingen',
    'beide',
    true
  ),
  (
    'meterstanden',
    'Meterstanden',
    'Geregistreerde meterstanden binnen de rapportperiode.',
    'meterstanden',
    'intern',
    true
  ),
  (
    'energieverbruik',
    'Energieverbruik',
    'Verbruik per bewoner per week voor elektriciteit, gas en water.',
    'energieverbruik',
    'beide',
    true
  ),
  (
    'opmerkingen',
    'Aanvullende opmerkingen',
    'Vrije aanvullende toelichting bij de rapportage.',
    'opmerkingen',
    'beide',
    true
  )
on conflict (code) do nothing;

alter table public.rapportblokken
  enable row level security;

alter table public.rapporttemplates
  enable row level security;

alter table public.rapporttemplateversies
  enable row level security;

alter table public.rapporttemplateblokken
  enable row level security;

drop policy if exists "Rapportblokken authenticated lezen"
  on public.rapportblokken;

create policy "Rapportblokken authenticated lezen"
  on public.rapportblokken
  for select
  to authenticated
  using (true);

drop policy if exists "Rapportblokken authenticated toevoegen"
  on public.rapportblokken;

create policy "Rapportblokken authenticated toevoegen"
  on public.rapportblokken
  for insert
  to authenticated
  with check (true);

drop policy if exists "Rapportblokken authenticated wijzigen"
  on public.rapportblokken;

create policy "Rapportblokken authenticated wijzigen"
  on public.rapportblokken
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Rapporttemplates authenticated lezen"
  on public.rapporttemplates;

create policy "Rapporttemplates authenticated lezen"
  on public.rapporttemplates
  for select
  to authenticated
  using (true);

drop policy if exists "Rapporttemplates authenticated toevoegen"
  on public.rapporttemplates;

create policy "Rapporttemplates authenticated toevoegen"
  on public.rapporttemplates
  for insert
  to authenticated
  with check (true);

drop policy if exists "Rapporttemplates authenticated wijzigen"
  on public.rapporttemplates;

create policy "Rapporttemplates authenticated wijzigen"
  on public.rapporttemplates
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Rapporttemplateversies authenticated lezen"
  on public.rapporttemplateversies;

create policy "Rapporttemplateversies authenticated lezen"
  on public.rapporttemplateversies
  for select
  to authenticated
  using (true);

drop policy if exists "Rapporttemplateversies authenticated toevoegen"
  on public.rapporttemplateversies;

create policy "Rapporttemplateversies authenticated toevoegen"
  on public.rapporttemplateversies
  for insert
  to authenticated
  with check (true);

drop policy if exists "Rapporttemplateversies authenticated wijzigen"
  on public.rapporttemplateversies;

create policy "Rapporttemplateversies authenticated wijzigen"
  on public.rapporttemplateversies
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Rapporttemplateblokken authenticated lezen"
  on public.rapporttemplateblokken;

create policy "Rapporttemplateblokken authenticated lezen"
  on public.rapporttemplateblokken
  for select
  to authenticated
  using (true);

drop policy if exists "Rapporttemplateblokken authenticated toevoegen"
  on public.rapporttemplateblokken;

create policy "Rapporttemplateblokken authenticated toevoegen"
  on public.rapporttemplateblokken
  for insert
  to authenticated
  with check (true);

drop policy if exists "Rapporttemplateblokken authenticated wijzigen"
  on public.rapporttemplateblokken;

create policy "Rapporttemplateblokken authenticated wijzigen"
  on public.rapporttemplateblokken
  for update
  to authenticated
  using (true)
  with check (true);
