create table if not exists public.documenten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  woning_id bigint not null
    references public.woningen(id)
    on update cascade
    on delete restrict,

  titel text not null,
  document_type text not null default 'overig'
    check (
      document_type in (
        'contract',
        'certificering',
        'keuring',
        'inspectie',
        'verzekering',
        'factuur',
        'rapportage',
        'handleiding',
        'identificatie',
        'overig'
      )
    ),

  omschrijving text,
  status text not null default 'actief'
    check (
      status in (
        'actief',
        'gearchiveerd'
      )
    ),

  vertrouwelijkheid text not null default 'intern'
    check (
      vertrouwelijkheid in (
        'intern',
        'vertrouwelijk',
        'extern_geschikt'
      )
    ),

  gearchiveerd_op timestamptz,
  archiefreden text,

  aangemaakt_door uuid
    references auth.users(id)
    on delete set null,

  gewijzigd_door uuid
    references auth.users(id)
    on delete set null,

  constraint documenten_titel_niet_leeg
    check (btrim(titel) <> ''),

  constraint documenten_archivering_consistent
    check (
      (
        status = 'actief'
        and gearchiveerd_op is null
      )
      or
      (
        status = 'gearchiveerd'
        and gearchiveerd_op is not null
      )
    )
);

create table if not exists public.documentversies (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  document_id bigint not null
    references public.documenten(id)
    on update cascade
    on delete restrict,

  versienummer integer not null
    check (versienummer > 0),

  bestandspad text not null unique,
  bestandsnaam text not null,
  mime_type text not null,
  bestandsgrootte bigint not null
    check (
      bestandsgrootte > 0
      and bestandsgrootte <= 20971520
    ),

  versie_opmerking text,

  geupload_door uuid
    references auth.users(id)
    on delete set null,

  constraint documentversies_bestandsnaam_niet_leeg
    check (btrim(bestandsnaam) <> ''),

  constraint documentversies_mime_type_niet_leeg
    check (btrim(mime_type) <> ''),

  constraint documentversies_document_versie_uniek
    unique (document_id, versienummer)
);

create index if not exists documenten_woning_id_idx
  on public.documenten(woning_id);

create index if not exists documenten_status_idx
  on public.documenten(status);

create index if not exists documenten_document_type_idx
  on public.documenten(document_type);

create index if not exists documenten_created_at_idx
  on public.documenten(created_at desc);

create index if not exists documentversies_document_id_idx
  on public.documentversies(document_id);

create index if not exists documentversies_created_at_idx
  on public.documentversies(created_at desc);

create or replace function public.documenten_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  new.gewijzigd_door = auth.uid();

  if new.status = 'gearchiveerd'
     and new.gearchiveerd_op is null then
    new.gearchiveerd_op = now();
  end if;

  if new.status = 'actief' then
    new.gearchiveerd_op = null;
    new.archiefreden = null;
  end if;

  return new;
end;
$$;

drop trigger if exists documenten_set_updated_at
  on public.documenten;

create trigger documenten_set_updated_at
before update on public.documenten
for each row
execute function public.documenten_set_updated_at();

create or replace view public.documenten_overzicht
with (security_invoker = true)
as
select
  document.id,
  document.created_at,
  document.updated_at,
  document.woning_id,
  document.titel,
  document.document_type,
  document.omschrijving,
  document.status,
  document.vertrouwelijkheid,
  document.gearchiveerd_op,
  document.archiefreden,
  document.aangemaakt_door,
  document.gewijzigd_door,
  laatste.id as laatste_versie_id,
  laatste.versienummer as laatste_versienummer,
  laatste.created_at as laatste_versie_created_at,
  laatste.bestandspad as laatste_bestandspad,
  laatste.bestandsnaam as laatste_bestandsnaam,
  laatste.mime_type as laatste_mime_type,
  laatste.bestandsgrootte as laatste_bestandsgrootte,
  laatste.versie_opmerking as laatste_versie_opmerking,
  coalesce(versies.aantal, 0)::integer as aantal_versies
from public.documenten document
left join lateral (
  select versie.*
  from public.documentversies versie
  where versie.document_id = document.id
  order by versie.versienummer desc
  limit 1
) laatste on true
left join lateral (
  select count(*) as aantal
  from public.documentversies versie
  where versie.document_id = document.id
) versies on true;

alter table public.documenten
  enable row level security;

alter table public.documentversies
  enable row level security;

drop policy if exists
  "Documenten authenticated lezen"
on public.documenten;

create policy
  "Documenten authenticated lezen"
on public.documenten
for select
to authenticated
using (true);

drop policy if exists
  "Documenten bevoegd toevoegen"
on public.documenten;

create policy
  "Documenten bevoegd toevoegen"
on public.documenten
for insert
to authenticated
with check (
  public.mag_administratie_beheren()
  and (
    aangemaakt_door is null
    or aangemaakt_door = auth.uid()
  )
);

drop policy if exists
  "Documenten bevoegd wijzigen"
on public.documenten;

create policy
  "Documenten bevoegd wijzigen"
on public.documenten
for update
to authenticated
using (
  public.mag_administratie_beheren()
)
with check (
  public.mag_administratie_beheren()
);

drop policy if exists
  "Documentversies authenticated lezen"
on public.documentversies;

create policy
  "Documentversies authenticated lezen"
on public.documentversies
for select
to authenticated
using (true);

drop policy if exists
  "Documentversies bevoegd toevoegen"
on public.documentversies;

create policy
  "Documentversies bevoegd toevoegen"
on public.documentversies
for insert
to authenticated
with check (
  public.mag_administratie_beheren()
  and (
    geupload_door is null
    or geupload_door = auth.uid()
  )
);

revoke all
on public.documenten
from anon;

revoke all
on public.documentversies
from anon;

grant select, insert, update
on public.documenten
to authenticated;

grant select, insert
on public.documentversies
to authenticated;

grant usage, select
on sequence public.documenten_id_seq
to authenticated;

grant usage, select
on sequence public.documentversies_id_seq
to authenticated;

grant select
on public.documenten_overzicht
to authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'woningdocumenten',
  'woningdocumenten',
  false,
  20971520,
  array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/heic',
    'image/heif'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists
  "Woningdocumenten authenticated lezen"
on storage.objects;

create policy
  "Woningdocumenten authenticated lezen"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'woningdocumenten'
);

drop policy if exists
  "Woningdocumenten bevoegd toevoegen"
on storage.objects;

create policy
  "Woningdocumenten bevoegd toevoegen"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'woningdocumenten'
  and public.mag_administratie_beheren()
);

drop policy if exists
  "Woningdocumenten bevoegd wijzigen"
on storage.objects;

create policy
  "Woningdocumenten bevoegd wijzigen"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'woningdocumenten'
  and public.mag_administratie_beheren()
)
with check (
  bucket_id = 'woningdocumenten'
  and public.mag_administratie_beheren()
);
